# Generated by Django 5.2.11 on 2026-02-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("territory", "0004_add_sezione_performance_indices"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sezioneelettorale",
            name="territory_sez_active_comune_idx",
        ),
        migrations.RemoveIndex(
            model_name="sezioneelettorale",
            name="territory_sez_active_mun_idx",
        ),
    ]
