# Generated by Django 5.2.10 on 2026-01-31 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elections", "0001_initial"),
        ("territory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROCEDURAL", "Procedurale"),
                            ("ACCESS", "Accesso al seggio"),
                            ("MATERIALS", "Materiali"),
                            ("INTIMIDATION", "Intimidazione"),
                            ("IRREGULARITY", "Irregolarità"),
                            ("TECHNICAL", "Tecnico"),
                            ("OTHER", "Altro"),
                        ],
                        max_length=20,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Bassa"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Critica"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="gravità",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aperta"),
                            ("IN_PROGRESS", "In corso"),
                            ("RESOLVED", "Risolta"),
                            ("CLOSED", "Chiusa"),
                            ("ESCALATED", "Escalata"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="stato",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titolo")),
                (
                    "description",
                    models.TextField(
                        help_text="Descrizione dettagliata dell'incidente",
                        verbose_name="descrizione",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando è avvenuto l'incidente",
                        null=True,
                        verbose_name="data/ora incidente",
                    ),
                ),
                (
                    "resolution",
                    models.TextField(
                        blank=True,
                        help_text="Come è stato risolto l'incidente",
                        null=True,
                        verbose_name="risoluzione",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data risoluzione"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="ultimo aggiornamento"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assegnato a",
                    ),
                ),
                (
                    "consultazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="elections.consultazioneelettorale",
                        verbose_name="consultazione",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="segnalante",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="risolto da",
                    ),
                ),
                (
                    "sezione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="territory.sezioneelettorale",
                        verbose_name="sezione",
                    ),
                ),
            ],
            options={
                "verbose_name": "segnalazione",
                "verbose_name_plural": "segnalazioni",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="contenuto")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, visibile solo agli operatori",
                        verbose_name="interno",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autore",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="incidents.incidentreport",
                        verbose_name="segnalazione",
                    ),
                ),
            ],
            options={
                "verbose_name": "commento",
                "verbose_name_plural": "commenti",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="incidents/%Y/%m/%d/", verbose_name="file"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Immagine"),
                            ("DOCUMENT", "Documento"),
                            ("VIDEO", "Video"),
                            ("OTHER", "Altro"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="tipo file",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="nome file"),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        help_text="In bytes", verbose_name="dimensione"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="descrizione"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data caricamento"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="caricato da",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="incidents.incidentreport",
                        verbose_name="segnalazione",
                    ),
                ),
            ],
            options={
                "verbose_name": "allegato",
                "verbose_name_plural": "allegati",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(
                fields=["consultazione", "status"],
                name="incidents_i_consult_98b863_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(
                fields=["sezione", "status"], name="incidents_i_sezione_ea9ce9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(
                fields=["reporter", "created_at"], name="incidents_i_reporte_1f9155_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(
                fields=["category", "severity"], name="incidents_i_categor_65a845_idx"
            ),
        ),
    ]
