# Generated by Django 5.2.11 on 2026-03-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='is_platform_issue',
            field=models.BooleanField(default=False, help_text='Se il problema riguarda la piattaforma AInaudi stessa (solo admin)', verbose_name='problema della piattaforma'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='is_verbalizzato',
            field=models.BooleanField(default=False, help_text='Se la segnalazione è stata verbalizzata ufficialmente nel registro di sezione', verbose_name='verbalizzato'),
        ),
    ]
