service: api
runtime: python311
env: standard
instance_class: F1

entrypoint: bash entrypoint.sh

env_variables:
  DJANGO_SETTINGS_MODULE: config.settings_api
  GOOGLE_CLOUD_PROJECT: ainaudi-prod
  DEBUG: "false"
  ALLOWED_HOSTS: ".appspot.com,.run.app,ainaudi.it,www.ainaudi.it,ainaudi-prod.appspot.com"

  # Database (Cloud SQL via Unix socket)
  DB_HOST: "/cloudsql/ainaudi-prod:europe-west1:ainaudi-db"
  DB_NAME: "ainaudi_db"
  DB_USER: "postgres"
  # DB_PASSWORD stored in Secret Manager

  # Google Cloud Storage (Media Files)
  USE_GCS: "true"
  GCS_BUCKET_NAME: "ainaudi-documents"
  GS_BUCKET_NAME: "ainaudi-documents"
  GS_DEFAULT_ACL: "publicRead"

  # CORS & CSRF Security
  CORS_ALLOWED_ORIGINS: "https://ainaudi-prod.appspot.com,https://ainaudi.it,https://www.ainaudi.it"
  CSRF_TRUSTED_ORIGINS: "https://ainaudi-prod.appspot.com,https://ainaudi.it,https://www.ainaudi.it"

  # Email (Amazon SES)
  # Credentials read from Secret Manager: email-host-user, email-host-password
  EMAIL_BACKEND: "django_ses.SESBackend"
  EMAIL_HOST: "email-smtp.eu-west-3.amazonaws.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  DEFAULT_FROM_EMAIL: "AINAUDI (M5S) <noreply@ainaudi.it>"
  AWS_SES_REGION_NAME: "eu-west-3"
  AWS_SES_REGION_ENDPOINT: "email.eu-west-3.amazonaws.com"

  # Frontend URL (for Magic Link)
  FRONTEND_URL: "https://ainaudi.it"

  # Feature Flags
  FEATURE_MAGIC_LINK: "true"
  FEATURE_M5S_SSO: "false"
  FEATURE_INCIDENT_REPORTS: "true"
  FEATURE_SECTION_IMPORT: "true"
  FEATURE_TEMPLATES_ENGINE: "true"
  FEATURE_AI_ASSISTANT: "false"  # AI runs on separate 'ai' service

# No static file handlers (API-only, admin is separate service)
handlers:
  - url: /.*
    script: auto
    secure: always

# Cloud SQL connection
beta_settings:
  cloud_sql_instances: ainaudi-prod:europe-west1:ainaudi-db

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 3
  min_idle_instances: 0
  max_idle_instances: 0
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
