service: api
runtime: python311
env: standard
instance_class: F4

entrypoint: bash entrypoint.sh

env_variables:
  DJANGO_SETTINGS_MODULE: config.settings
  GOOGLE_CLOUD_PROJECT: ainaudi-prod
  DEBUG: "false"
  ALLOWED_HOSTS: ".appspot.com,.run.app"

  # Database (Cloud SQL via Unix socket)
  DB_HOST: "/cloudsql/ainaudi-prod:europe-west1:ainaudi-db"
  DB_NAME: "ainaudi_db"
  DB_USER: "postgres"
  # DB_PASSWORD stored in Secret Manager

  # Google Cloud Storage (Media Files)
  USE_GCS: "true"
  GCS_BUCKET_NAME: "ainaudi-documents"
  GS_BUCKET_NAME: "ainaudi-documents"
  GS_DEFAULT_ACL: "publicRead"

  # CORS & CSRF Security
  CORS_ALLOWED_ORIGINS: "https://ainaudi-prod.appspot.com"
  CSRF_TRUSTED_ORIGINS: "https://ainaudi-prod.appspot.com"

  # Email (Gmail SMTP)
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  EMAIL_HOST_USER: "s.federici@gmail.com"
  # EMAIL_HOST_PASSWORD stored in Secret Manager (Gmail App Password)
  DEFAULT_FROM_EMAIL: "AINAUDI (M5S) - Simone Federici <s.federici@gmail.com>"

  # Frontend URL (for Magic Link)
  FRONTEND_URL: "https://ainaudi-prod.appspot.com"

  # Feature Flags
  FEATURE_MAGIC_LINK: "true"
  FEATURE_M5S_SSO: "false"
  FEATURE_INCIDENT_REPORTS: "true"
  FEATURE_SECTION_IMPORT: "true"
  FEATURE_TEMPLATES_ENGINE: "true"
  FEATURE_AI_ASSISTANT: "true"

  # Vertex AI Configuration (Gemini + Embeddings)
  VERTEX_AI_PROJECT: "ainaudi-prod"
  VERTEX_AI_LOCATION: "europe-west1"  # Belgio (Gemini disponibile)

handlers:
  # Admin static files (CSS/JS/fonts) - cache 6 months
  - url: /static/admin
    static_dir: staticfiles/admin/
    secure: always
    expiration: 180d

  # DRF static files - cache 6 months
  - url: /static/rest_framework
    static_dir: staticfiles/rest_framework/
    secure: always
    expiration: 180d

  # Other static files
  - url: /static
    static_dir: staticfiles/
    secure: always

  # All other requests go to Django
  - url: /.*
    script: auto
    secure: always

# Cloud SQL connection
beta_settings:
  cloud_sql_instances: ainaudi-prod:europe-west1:ainaudi-db

# Automatic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_idle_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
