# Generated by Django 5.2.11 on 2026-02-21 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0013_rename_data_datisc_datisez_version_idx_data_datisc_dati_se_edea83_idx_and_more'),
        ('elections', '0004_add_data_version_and_has_subdelegations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='titolo')),
                ('description', models.TextField(blank=True, verbose_name='descrizione')),
                ('start_at', models.DateTimeField(verbose_name='inizio')),
                ('end_at', models.DateTimeField(verbose_name='fine')),
                ('external_url', models.URLField(blank=True, help_text='Es. link Zoom per meeting online', verbose_name='link esterno')),
                ('status', models.CharField(choices=[('ACTIVE', 'Attivo'), ('CANCELLED', 'Annullato')], default='ACTIVE', max_length=20, verbose_name='stato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('consultazione', models.ForeignKey(blank=True, help_text='Se impostato, le notifiche vengono inviate agli utenti della consultazione', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='elections.consultazioneelettorale', verbose_name='consultazione')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventi',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='titolo')),
                ('body', models.TextField(verbose_name='corpo')),
                ('deep_link', models.CharField(help_text='Es. /events/<id> o /assignments/<id>', max_length=500, verbose_name='deep link')),
                ('scheduled_at', models.DateTimeField(verbose_name='programmata per')),
                ('channel', models.CharField(choices=[('PUSH', 'Push'), ('EMAIL', 'Email'), ('BOTH', 'Push + Email')], default='BOTH', max_length=10, verbose_name='canale')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmata'), ('SENT', 'Inviata'), ('FAILED', 'Fallita'), ('CANCELLED', 'Annullata')], default='SCHEDULED', max_length=20, verbose_name='stato')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='inviata il')),
                ('cloud_task_name', models.CharField(blank=True, help_text='Full resource name del task GCP per cancellazione', max_length=500, verbose_name='nome Cloud Task')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creata il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornata il')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.event', verbose_name='evento')),
                ('section_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='data.sectionassignment', verbose_name='assegnazione sezione')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'notifica',
                'verbose_name_plural': 'notifiche',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(help_text='Firebase Cloud Messaging registration token', verbose_name='token FCM')),
                ('platform', models.CharField(choices=[('WEB', 'Web (PWA)'), ('ANDROID', 'Android'), ('IOS', 'iOS'), ('UNKNOWN', 'Sconosciuto')], default='WEB', max_length=10, verbose_name='piattaforma')),
                ('is_active', models.BooleanField(default=True, verbose_name='attivo')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='ultimo utilizzo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'token dispositivo',
                'verbose_name_plural': 'token dispositivi',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'token'), name='unique_device_token_per_user')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_at'], name='notificatio_status_6cbd15_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['consultazione', 'status'], name='notificatio_consult_420c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_a9c93f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event', 'status'], name='notificatio_event_i_df031f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['section_assignment', 'status'], name='notificatio_section_2999b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', False), ('section_assignment__isnull', True)), models.Q(('event__isnull', True), ('section_assignment__isnull', False)), _connector='OR'), name='notification_xor_source'),
        ),
    ]
