# Generated by Django 5.2.11 on 2026-02-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('territory', '0006_sezione_geocode_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comuni',
            field=models.ManyToManyField(blank=True, help_text='Filtro aggiuntivo per comuni.', to='territory.comune', verbose_name='comuni'),
        ),
        migrations.AddField(
            model_name='event',
            name='province',
            field=models.ManyToManyField(blank=True, help_text='Filtro aggiuntivo per province.', to='territory.provincia', verbose_name='province'),
        ),
        migrations.AddField(
            model_name='event',
            name='regioni',
            field=models.ManyToManyField(blank=True, help_text='Se vuoto, evento visibile a tutti. Se valorizzato, solo utenti con sezioni in queste regioni.', to='territory.regione', verbose_name='regioni'),
        ),
    ]
