# Generated by Django 5.2.11 on 2026-02-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_event_territory_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="origin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="window.location.origin del browser (es. https://ainaudi.it)",
                max_length=255,
                verbose_name="origin",
            ),
        ),
    ]
