# Generated by Django 5.2.10 on 2026-01-31 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice_istat",
                    models.CharField(
                        help_text="Codice ISTAT a 6 cifre",
                        max_length=6,
                        unique=True,
                        verbose_name="codice ISTAT",
                    ),
                ),
                (
                    "codice_catastale",
                    models.CharField(
                        help_text="Codice Belfiore/catastale",
                        max_length=4,
                        unique=True,
                        verbose_name="codice catastale",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "popolazione",
                    models.IntegerField(
                        blank=True,
                        help_text="Popolazione residente (per determinare sistema elettorale)",
                        null=True,
                        verbose_name="popolazione",
                    ),
                ),
                (
                    "cap",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="CAP"
                    ),
                ),
            ],
            options={
                "verbose_name": "comune",
                "verbose_name_plural": "comuni",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice_istat",
                    models.CharField(
                        help_text="Codice ISTAT a 3 cifre",
                        max_length=3,
                        unique=True,
                        verbose_name="codice ISTAT",
                    ),
                ),
                (
                    "sigla",
                    models.CharField(
                        help_text='Sigla automobilistica (es. "RM")',
                        max_length=2,
                        verbose_name="sigla",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "is_citta_metropolitana",
                    models.BooleanField(
                        default=False, verbose_name="città metropolitana"
                    ),
                ),
            ],
            options={
                "verbose_name": "provincia",
                "verbose_name_plural": "province",
                "ordering": ["regione__codice_istat", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Regione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice_istat",
                    models.CharField(
                        help_text='Codice ISTAT a 2 cifre (es. "12" per Lazio)',
                        max_length=2,
                        unique=True,
                        verbose_name="codice ISTAT",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "statuto_speciale",
                    models.BooleanField(
                        default=False,
                        help_text="Regione a statuto speciale",
                        verbose_name="statuto speciale",
                    ),
                ),
            ],
            options={
                "verbose_name": "regione",
                "verbose_name_plural": "regioni",
                "ordering": ["codice_istat"],
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField(verbose_name="numero")),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        help_text='Nome del municipio (es. "Municipio I - Centro Storico")',
                        max_length=100,
                        verbose_name="nome",
                    ),
                ),
                (
                    "comune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="municipi",
                        to="territorio.comune",
                        verbose_name="comune",
                    ),
                ),
            ],
            options={
                "verbose_name": "municipio",
                "verbose_name_plural": "municipi",
                "ordering": ["comune", "numero"],
                "unique_together": {("comune", "numero")},
            },
        ),
        migrations.AddField(
            model_name="comune",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comuni",
                to="territorio.provincia",
                verbose_name="provincia",
            ),
        ),
        migrations.AddField(
            model_name="provincia",
            name="regione",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="province",
                to="territorio.regione",
                verbose_name="regione",
            ),
        ),
        migrations.CreateModel(
            name="SezioneElettorale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.IntegerField(
                        help_text="Numero progressivo nel comune",
                        verbose_name="numero sezione",
                    ),
                ),
                (
                    "indirizzo",
                    models.CharField(
                        blank=True,
                        help_text="Indirizzo del seggio",
                        max_length=255,
                        null=True,
                        verbose_name="indirizzo",
                    ),
                ),
                (
                    "denominazione",
                    models.CharField(
                        blank=True,
                        help_text='Nome del seggio (es. "Scuola Elementare Mazzini")',
                        max_length=255,
                        null=True,
                        verbose_name="denominazione",
                    ),
                ),
                (
                    "n_elettori",
                    models.IntegerField(
                        blank=True,
                        help_text="Numero di elettori iscritti",
                        null=True,
                        verbose_name="numero elettori",
                    ),
                ),
                ("is_attiva", models.BooleanField(default=True, verbose_name="attiva")),
                (
                    "latitudine",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitudine",
                    ),
                ),
                (
                    "longitudine",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitudine",
                    ),
                ),
                (
                    "comune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sezioni",
                        to="territorio.comune",
                        verbose_name="comune",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sezioni",
                        to="territorio.municipio",
                        verbose_name="municipio",
                    ),
                ),
            ],
            options={
                "verbose_name": "sezione elettorale",
                "verbose_name_plural": "sezioni elettorali",
                "ordering": ["comune", "numero"],
                "unique_together": {("comune", "numero")},
            },
        ),
    ]
