# Generated by Django 5.2.10 on 2026-02-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("territorio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerritorialPartitionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partition_type",
                    models.CharField(
                        choices=[
                            ("EU_CIRCOSCRIZIONE", "Circoscrizione Europee"),
                            ("CAMERA_CIRCOSCRIZIONE", "Circoscrizione Camera"),
                            ("SENATO_CIRCOSCRIZIONE", "Circoscrizione Senato"),
                            (
                                "COLLEGIO_UNINOMINALE_CAMERA",
                                "Collegio Uninominale Camera",
                            ),
                            (
                                "COLLEGIO_PLURINOMINALE_CAMERA",
                                "Collegio Plurinominale Camera",
                            ),
                            (
                                "COLLEGIO_UNINOMINALE_SENATO",
                                "Collegio Uninominale Senato",
                            ),
                            (
                                "COLLEGIO_PLURINOMINALE_SENATO",
                                "Collegio Plurinominale Senato",
                            ),
                        ],
                        max_length=40,
                        verbose_name="tipo partizione",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text='es. "Circoscrizioni Europee", "Collegi Camera 2020"',
                        max_length=100,
                        verbose_name="nome",
                    ),
                ),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="descrizione"),
                ),
                (
                    "normative_ref",
                    models.CharField(
                        blank=True,
                        help_text='es. "Legge 165/2017", "DPR 361/1957"',
                        max_length=200,
                        verbose_name="riferimento normativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "set partizioni territoriali",
                "verbose_name_plural": "set partizioni territoriali",
            },
        ),
        migrations.CreateModel(
            name="TerritorialPartitionUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice",
                    models.CharField(
                        help_text='es. "NORD_OVEST", "LAZIO_1", "U01"',
                        max_length=30,
                        verbose_name="codice",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "parent_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Per gerarchie: collegio uninominale → collegio plurinominale → circoscrizione",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_units",
                        to="territorio.territorialpartitionunit",
                        verbose_name="unità padre",
                    ),
                ),
                (
                    "partition_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="territorio.territorialpartitionset",
                        verbose_name="set partizioni",
                    ),
                ),
            ],
            options={
                "verbose_name": "unità partizione territoriale",
                "verbose_name_plural": "unità partizioni territoriali",
                "ordering": ["partition_set", "codice"],
                "unique_together": {("partition_set", "codice")},
            },
        ),
        migrations.CreateModel(
            name="TerritorialPartitionMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partition_memberships",
                        to="territorio.comune",
                        verbose_name="comune",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partition_memberships",
                        to="territorio.provincia",
                        verbose_name="provincia",
                    ),
                ),
                (
                    "regione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partition_memberships",
                        to="territorio.regione",
                        verbose_name="regione",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="territorio.territorialpartitionunit",
                        verbose_name="unità partizione",
                    ),
                ),
            ],
            options={
                "verbose_name": "appartenenza partizione",
                "verbose_name_plural": "appartenenze partizioni",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("comune__isnull", False),
                                ("provincia__isnull", True),
                                ("regione__isnull", True),
                            ),
                            models.Q(
                                ("comune__isnull", True),
                                ("provincia__isnull", False),
                                ("regione__isnull", True),
                            ),
                            models.Q(
                                ("comune__isnull", True),
                                ("provincia__isnull", True),
                                ("regione__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="membership_one_territory_level",
                    )
                ],
            },
        ),
    ]
