# Generated by Django 5.2.10 on 2026-02-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0004_telefono_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rdlregistration",
            name="comune_nascita",
            field=models.CharField(
                default="", max_length=100, verbose_name="comune di nascita"
            ),
        ),
        migrations.AlterField(
            model_name="rdlregistration",
            name="comune_residenza",
            field=models.CharField(
                default="", max_length=100, verbose_name="residente nel comune di"
            ),
        ),
        migrations.AlterField(
            model_name="rdlregistration",
            name="data_nascita",
            field=models.DateField(
                default="2000-01-01", verbose_name="data di nascita"
            ),
        ),
        migrations.AlterField(
            model_name="rdlregistration",
            name="indirizzo_residenza",
            field=models.CharField(
                default="", max_length=255, verbose_name="indirizzo di residenza"
            ),
        ),
    ]
