# Generated by Django 5.2.10 on 2026-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_add_partition_bindings_remove_old_circumscriptions"),
        ("sections", "0008_rdlregistration_campagna_consultazione"),
        ("territorio", "0002_add_territorial_partitions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sectionassignment",
            name="sections_se_user_id_a47914_idx",
        ),
        migrations.RemoveField(
            model_name="datisezione",
            name="inserito_da",
        ),
        migrations.RemoveField(
            model_name="datisezione",
            name="verified_by",
        ),
        migrations.RemoveField(
            model_name="rdlregistration",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="rdlregistration",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sectionassignment",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="sectionassignment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sectiondatahistory",
            name="modificato_da",
        ),
        migrations.AddField(
            model_name="datisezione",
            name="inserito_da_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="inserito da (email)"
            ),
        ),
        migrations.AddField(
            model_name="datisezione",
            name="verified_by_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="verificato da (email)"
            ),
        ),
        migrations.AddField(
            model_name="rdlregistration",
            name="approved_by_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="approvato da (email)"
            ),
        ),
        migrations.AddField(
            model_name="sectionassignment",
            name="assigned_by_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="assegnato da (email)"
            ),
        ),
        migrations.AddField(
            model_name="sectiondatahistory",
            name="modificato_da_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="modificato da (email)"
            ),
        ),
        migrations.AlterField(
            model_name="rdlregistration",
            name="comune_nascita",
            field=models.CharField(max_length=100, verbose_name="comune di nascita"),
        ),
        migrations.AlterField(
            model_name="rdlregistration",
            name="comune_residenza",
            field=models.CharField(
                max_length=100, verbose_name="residente nel comune di"
            ),
        ),
        migrations.AlterField(
            model_name="rdlregistration",
            name="data_nascita",
            field=models.DateField(verbose_name="data di nascita"),
        ),
        migrations.AlterField(
            model_name="rdlregistration",
            name="indirizzo_residenza",
            field=models.CharField(
                max_length=255, verbose_name="indirizzo di residenza"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionassignment",
            index=models.Index(
                fields=["rdl_registration", "consultazione"],
                name="sections_se_rdl_reg_f85e02_idx",
            ),
        ),
    ]
