# DEPRECATED - Google App Engine PDF Worker Service
#
# **Status**: OBSOLETO - Non più utilizzato
#
# Questo servizio GAE gestiva la generazione asincrona di PDF.
# La generazione PDF è ora sincrona nel backend Django.
#
# Data deprecazione: Febbraio 2026
#
# service: pdf
# runtime: python39
# env: standard
# instance_class: F2
#
# handlers:
#   - url: /api/generate/multiple
#     script: auto
#     secure: always
#   - url: /api/generate/single
#     script: auto
#     secure: always
#
# automatic_scaling:
#   min_idle_instances: 0
#   max_idle_instances: 1
#   min_pending_latency: 30ms
#   max_pending_latency: 200ms
#   max_instances: 10
