# Generated by Django 5.2.10 on 2026-01-31 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elections", "0001_initial"),
        ("territory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DelegationRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("ADMIN_TO_DELEGATE", "Admin → Delegato"),
                            ("DELEGATE_TO_SUBDELEGATE", "Delegato → Sub-delegato"),
                            ("SUBDELEGATE_TO_RDL", "Sub-delegato → RDL"),
                            ("DIRECT_TO_RDL", "Diretto → RDL"),
                        ],
                        max_length=30,
                        verbose_name="tipo relazione",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        help_text="Data inizio validità", verbose_name="valido da"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data fine validità (opzionale)",
                        null=True,
                        verbose_name="valido fino a",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="attiva")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data revoca"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="note")),
                (
                    "consultazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegation_relationships",
                        to="elections.consultazioneelettorale",
                        verbose_name="consultazione",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegations_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        help_text="Chi riceve la delega",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="delegato",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        help_text="Chi conferisce la delega",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="delegante",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegations_revoked",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revocato da",
                    ),
                ),
                (
                    "scope_comune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegation_relationships",
                        to="territory.comune",
                        verbose_name="comune",
                    ),
                ),
                (
                    "scope_municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegation_relationships",
                        to="territory.municipio",
                        verbose_name="municipio",
                    ),
                ),
                (
                    "scope_provincia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegation_relationships",
                        to="territory.provincia",
                        verbose_name="provincia",
                    ),
                ),
                (
                    "scope_regione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegation_relationships",
                        to="territory.regione",
                        verbose_name="regione",
                    ),
                ),
            ],
            options={
                "verbose_name": "relazione di delega",
                "verbose_name_plural": "relazioni di delega",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FreezeBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='es. "Freeze Roma 15/05/2025"',
                        max_length=100,
                        verbose_name="nome",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descrizione"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Bozza"),
                            ("FROZEN", "Congelato"),
                            ("APPROVED", "Approvato"),
                            ("SENT", "Inviato"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="stato",
                    ),
                ),
                (
                    "snapshot_data",
                    models.JSONField(
                        default=dict,
                        help_text="Stato congelato delle deleghe e assegnazioni",
                        verbose_name="dati snapshot",
                    ),
                ),
                (
                    "frozen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data congelamento"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data approvazione"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freeze_batches_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approvato da",
                    ),
                ),
                (
                    "consultazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freeze_batches",
                        to="elections.consultazioneelettorale",
                        verbose_name="consultazione",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freeze_batches_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "scope_comune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freeze_batches",
                        to="territory.comune",
                        verbose_name="comune",
                    ),
                ),
                (
                    "scope_provincia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freeze_batches",
                        to="territory.provincia",
                        verbose_name="provincia",
                    ),
                ),
                (
                    "scope_regione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freeze_batches",
                        to="territory.regione",
                        verbose_name="regione",
                    ),
                ),
            ],
            options={
                "verbose_name": "batch congelamento",
                "verbose_name_plural": "batch congelamenti",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProxyDelegationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUALE", "Individuale"),
                            ("RIEPILOGATIVO", "Riepilogativo"),
                        ],
                        max_length=20,
                        verbose_name="tipo documento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Bozza"),
                            ("READY", "Pronto"),
                            ("APPROVED", "Approvato"),
                            ("SENT", "Inviato"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="stato",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="deleghe/%Y/%m/",
                        verbose_name="file PDF",
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True,
                        help_text="URL su Cloud Storage",
                        null=True,
                        verbose_name="URL PDF",
                    ),
                ),
                (
                    "template_data",
                    models.JSONField(
                        blank=True,
                        help_text="Dati usati per generare il PDF",
                        null=True,
                        verbose_name="dati template",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data generazione"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data approvazione"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data invio"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approvato da",
                    ),
                ),
                (
                    "delegation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Per documenti individuali",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="delegations.delegationrelationship",
                        verbose_name="delega",
                    ),
                ),
                (
                    "freeze_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="delegations.freezebatch",
                        verbose_name="batch",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_generated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="generato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento delega",
                "verbose_name_plural": "documenti delega",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="delegationrelationship",
            index=models.Index(
                fields=["principal", "consultazione"],
                name="delegations_princip_855b5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="delegationrelationship",
            index=models.Index(
                fields=["delegate", "consultazione"],
                name="delegations_delegat_a87724_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="delegationrelationship",
            index=models.Index(
                fields=["relationship_type", "is_active"],
                name="delegations_relatio_4bc790_idx",
            ),
        ),
    ]
