# Generated by Django 5.2.10 on 2026-02-01 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0001_initial"),
        ("elections", "0001_initial"),
        ("territorio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proxydelegationdocument",
            name="delegation",
        ),
        migrations.RemoveField(
            model_name="freezebatch",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="freezebatch",
            name="consultazione",
        ),
        migrations.RemoveField(
            model_name="freezebatch",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="freezebatch",
            name="scope_comune",
        ),
        migrations.RemoveField(
            model_name="freezebatch",
            name="scope_provincia",
        ),
        migrations.RemoveField(
            model_name="freezebatch",
            name="scope_regione",
        ),
        migrations.RemoveField(
            model_name="proxydelegationdocument",
            name="freeze_batch",
        ),
        migrations.RemoveField(
            model_name="proxydelegationdocument",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="proxydelegationdocument",
            name="generated_by",
        ),
        migrations.CreateModel(
            name="DelegatoDiLista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cognome", models.CharField(max_length=100, verbose_name="cognome")),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "luogo_nascita",
                    models.CharField(max_length=100, verbose_name="luogo di nascita"),
                ),
                ("data_nascita", models.DateField(verbose_name="data di nascita")),
                (
                    "carica",
                    models.CharField(
                        choices=[
                            ("DEPUTATO", "Deputato"),
                            ("SENATORE", "Senatore"),
                            ("CONSIGLIERE_REGIONALE", "Consigliere Regionale"),
                            ("EURODEPUTATO", "Europarlamentare"),
                        ],
                        max_length=30,
                        verbose_name="carica",
                    ),
                ),
                (
                    "circoscrizione",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="circoscrizione"
                    ),
                ),
                ("data_nomina", models.DateField(verbose_name="data nomina")),
                (
                    "numero_protocollo_nomina",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="numero protocollo"
                    ),
                ),
                (
                    "documento_nomina",
                    models.FileField(
                        blank=True,
                        help_text="PDF della nomina dal Partito",
                        null=True,
                        upload_to="deleghe/nomine_partito/",
                        verbose_name="documento nomina",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefono"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="data modifica"),
                ),
                (
                    "consultazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegati_lista",
                        to="elections.consultazioneelettorale",
                        verbose_name="consultazione",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleghe_lista",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="account utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delegato di Lista",
                "verbose_name_plural": "Delegati di Lista",
                "ordering": ["consultazione", "cognome", "nome"],
                "unique_together": {
                    ("consultazione", "cognome", "nome", "data_nascita")
                },
            },
        ),
        migrations.CreateModel(
            name="SubDelega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cognome", models.CharField(max_length=100, verbose_name="cognome")),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "luogo_nascita",
                    models.CharField(max_length=100, verbose_name="luogo di nascita"),
                ),
                ("data_nascita", models.DateField(verbose_name="data di nascita")),
                (
                    "domicilio",
                    models.CharField(
                        help_text="Indirizzo completo di residenza/domicilio",
                        max_length=255,
                        verbose_name="domicilio",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        help_text="es. Carta d'identità, Patente",
                        max_length=50,
                        verbose_name="tipo documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=50, verbose_name="numero documento"),
                ),
                (
                    "municipi",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista di numeri di municipio (solo per Roma)",
                        verbose_name="municipi",
                    ),
                ),
                ("data_delega", models.DateField(verbose_name="data delega")),
                (
                    "numero_protocollo",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="numero protocollo"
                    ),
                ),
                (
                    "firma_autenticata",
                    models.BooleanField(
                        default=False, verbose_name="firma autenticata"
                    ),
                ),
                (
                    "data_autenticazione",
                    models.DateField(
                        blank=True, null=True, verbose_name="data autenticazione"
                    ),
                ),
                (
                    "autenticatore",
                    models.CharField(
                        blank=True,
                        help_text="Chi ha autenticato la firma (es. Segretario Comunale, Notaio)",
                        max_length=255,
                        verbose_name="autenticatore",
                    ),
                ),
                (
                    "documento_delega",
                    models.FileField(
                        blank=True,
                        help_text="PDF della sub-delega firmata e autenticata",
                        null=True,
                        upload_to="deleghe/sub_deleghe/",
                        verbose_name="documento delega",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefono"
                    ),
                ),
                ("is_attiva", models.BooleanField(default=True, verbose_name="attiva")),
                (
                    "revocata_il",
                    models.DateField(blank=True, null=True, verbose_name="revocata il"),
                ),
                (
                    "motivo_revoca",
                    models.TextField(blank=True, verbose_name="motivo revoca"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="data modifica"),
                ),
                (
                    "comuni",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Comuni di competenza",
                        related_name="sub_deleghe",
                        to="territorio.comune",
                        verbose_name="comuni",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_deleghe_create",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "delegato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_deleghe",
                        to="delegations.delegatodilista",
                        verbose_name="delegato",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_deleghe_ricevute",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="account utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-Delega",
                "verbose_name_plural": "Sub-Deleghe",
                "ordering": ["delegato", "cognome", "nome"],
            },
        ),
        migrations.CreateModel(
            name="DesignazioneRDL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ruolo",
                    models.CharField(
                        choices=[
                            ("EFFETTIVO", "Effettivo"),
                            ("SUPPLENTE", "Supplente"),
                        ],
                        max_length=10,
                        verbose_name="ruolo",
                    ),
                ),
                ("cognome", models.CharField(max_length=100, verbose_name="cognome")),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "luogo_nascita",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="luogo di nascita"
                    ),
                ),
                (
                    "data_nascita",
                    models.DateField(
                        blank=True, null=True, verbose_name="data di nascita"
                    ),
                ),
                (
                    "domicilio",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="domicilio"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefono"
                    ),
                ),
                (
                    "documento_designazione",
                    models.FileField(
                        blank=True,
                        help_text="PDF della designazione con catena deleghe",
                        null=True,
                        upload_to="deleghe/designazioni_rdl/",
                        verbose_name="documento designazione",
                    ),
                ),
                (
                    "data_generazione_documento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data generazione documento"
                    ),
                ),
                (
                    "data_designazione",
                    models.DateField(
                        auto_now_add=True, verbose_name="data designazione"
                    ),
                ),
                ("is_attiva", models.BooleanField(default=True, verbose_name="attiva")),
                (
                    "revocata_il",
                    models.DateField(blank=True, null=True, verbose_name="revocata il"),
                ),
                (
                    "motivo_revoca",
                    models.TextField(blank=True, verbose_name="motivo revoca"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="data modifica"),
                ),
                (
                    "sezione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designazioni_rdl",
                        to="territorio.sezioneelettorale",
                        verbose_name="sezione",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="designazioni_rdl",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="account utente",
                    ),
                ),
                (
                    "sub_delega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designazioni_rdl",
                        to="delegations.subdelega",
                        verbose_name="sub-delega",
                    ),
                ),
            ],
            options={
                "verbose_name": "Designazione RDL",
                "verbose_name_plural": "Designazioni RDL",
                "ordering": ["sezione", "ruolo"],
            },
        ),
        migrations.CreateModel(
            name="BatchGenerazioneDocumenti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INDIVIDUALE", "Moduli Individuali"),
                            ("RIEPILOGATIVO", "Modulo Riepilogativo"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("BOZZA", "Bozza"),
                            ("GENERATO", "Generato"),
                            ("INVIATO", "Inviato"),
                        ],
                        default="BOZZA",
                        max_length=20,
                        verbose_name="stato",
                    ),
                ),
                (
                    "solo_sezioni",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista di ID sezioni da includere (vuoto = tutte)",
                        verbose_name="solo sezioni",
                    ),
                ),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="deleghe/batch/",
                        verbose_name="documento",
                    ),
                ),
                (
                    "data_generazione",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data generazione"
                    ),
                ),
                (
                    "n_designazioni",
                    models.IntegerField(default=0, verbose_name="numero designazioni"),
                ),
                (
                    "n_pagine",
                    models.IntegerField(default=0, verbose_name="numero pagine"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "sub_delega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_documenti",
                        to="delegations.subdelega",
                        verbose_name="sub-delega",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Generazione Documenti",
                "verbose_name_plural": "Batch Generazione Documenti",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="DelegationRelationship",
        ),
        migrations.DeleteModel(
            name="FreezeBatch",
        ),
        migrations.DeleteModel(
            name="ProxyDelegationDocument",
        ),
        migrations.AddConstraint(
            model_name="designazionerdl",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_attiva", True)),
                fields=("sezione", "ruolo"),
                name="unique_rdl_attivo_per_sezione_ruolo",
            ),
        ),
    ]
