# Generated by Django 5.2.10 on 2026-02-01 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0002_remove_proxydelegationdocument_delegation_and_more"),
        ("territory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="designazionerdl",
            name="delegato",
            field=models.ForeignKey(
                blank=True,
                help_text="Se la designazione è fatta direttamente dal Delegato",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designazioni_rdl_dirette",
                to="delegations.delegatodilista",
                verbose_name="delegato",
            ),
        ),
        migrations.AlterField(
            model_name="designazionerdl",
            name="sub_delega",
            field=models.ForeignKey(
                blank=True,
                help_text="Se la designazione è fatta dal Sub-Delegato",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designazioni_rdl",
                to="delegations.subdelega",
                verbose_name="sub-delega",
            ),
        ),
        migrations.AddConstraint(
            model_name="designazionerdl",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delegato__isnull", False),
                    ("sub_delega__isnull", False),
                    _connector="OR",
                ),
                name="designazione_ha_delegante",
            ),
        ),
    ]
