# Generated by Django 5.2.10 on 2026-02-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0004_add_consigliere_capitolino"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delegatodilista",
            name="carica",
            field=models.CharField(
                choices=[
                    ("DEPUTATO", "Deputato"),
                    ("SENATORE", "Senatore"),
                    ("CONSIGLIERE_REGIONALE", "Consigliere Regionale"),
                    ("CONSIGLIERE_COMUNALE", "Consigliere Comunale"),
                    ("EURODEPUTATO", "Europarlamentare"),
                ],
                max_length=30,
                verbose_name="carica",
            ),
        ),
    ]
