# Generated by Django 5.2.10 on 2026-02-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0005_remove_consigliere_capitolino"),
        ("territorio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegatodilista",
            name="territorio_comuni",
            field=models.ManyToManyField(
                blank=True,
                help_text="Comuni di competenza",
                related_name="delegati_lista",
                to="territorio.comune",
                verbose_name="comuni",
            ),
        ),
        migrations.AddField(
            model_name="delegatodilista",
            name="territorio_municipi",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista di numeri di municipio (solo per Roma)",
                verbose_name="municipi",
            ),
        ),
        migrations.AddField(
            model_name="delegatodilista",
            name="territorio_province",
            field=models.ManyToManyField(
                blank=True,
                help_text="Province di competenza",
                related_name="delegati_lista",
                to="territorio.provincia",
                verbose_name="province",
            ),
        ),
        migrations.AddField(
            model_name="delegatodilista",
            name="territorio_regioni",
            field=models.ManyToManyField(
                blank=True,
                help_text="Regioni di competenza",
                related_name="delegati_lista",
                to="territorio.regione",
                verbose_name="regioni",
            ),
        ),
        migrations.AlterField(
            model_name="delegatodilista",
            name="circoscrizione",
            field=models.CharField(
                blank=True,
                help_text="Campo descrittivo, usare i campi territorio per i permessi",
                max_length=100,
                verbose_name="circoscrizione (testo)",
            ),
        ),
    ]
