# Generated by Django 5.2.10 on 2026-02-01 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0006_add_territorio_delegato"),
        ("territorio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="designazionerdl",
            name="unique_rdl_attivo_per_sezione_ruolo",
        ),
        migrations.AddField(
            model_name="designazionerdl",
            name="approvata_da",
            field=models.ForeignKey(
                blank=True,
                help_text="Delegato che ha approvato la bozza",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designazioni_approvate",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approvata da",
            ),
        ),
        migrations.AddField(
            model_name="designazionerdl",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designazioni_create",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creato da",
            ),
        ),
        migrations.AddField(
            model_name="designazionerdl",
            name="data_approvazione",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="data approvazione"
            ),
        ),
        migrations.AddField(
            model_name="designazionerdl",
            name="stato",
            field=models.CharField(
                choices=[
                    ("BOZZA", "Bozza (in attesa approvazione Delegato)"),
                    ("CONFERMATA", "Confermata"),
                    ("REVOCATA", "Revocata"),
                ],
                default="CONFERMATA",
                help_text="BOZZA = mappatura in attesa di approvazione del Delegato",
                max_length=15,
                verbose_name="stato",
            ),
        ),
        migrations.AddField(
            model_name="subdelega",
            name="tipo_delega",
            field=models.CharField(
                choices=[
                    ("FIRMA_AUTENTICATA", "Con firma autenticata (può designare RDL)"),
                    ("MAPPATURA", "Solo mappatura sezioni (Delegato firma)"),
                ],
                default="MAPPATURA",
                help_text="Determina se il Sub-Delegato può designare direttamente o solo preparare mappature",
                max_length=20,
                verbose_name="tipo delega",
            ),
        ),
        migrations.AddConstraint(
            model_name="designazionerdl",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_attiva", True), ("stato", "CONFERMATA")),
                fields=("sezione", "ruolo"),
                name="unique_rdl_confermato_per_sezione_ruolo",
            ),
        ),
    ]
