# Generated by Django 5.2.10 on 2026-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0009_campagnareclutamento"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="campagnareclutamento",
            new_name="delegations_slug_c38355_idx",
            old_name="delegations_slug_d3b8d0_idx",
        ),
        migrations.RenameIndex(
            model_name="campagnareclutamento",
            new_name="delegations_stato_7456e2_idx",
            old_name="delegations_stato_d6f547_idx",
        ),
        migrations.RemoveField(
            model_name="batchgenerazionedocumenti",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="campagnareclutamento",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="delegatodilista",
            name="user",
        ),
        migrations.RemoveField(
            model_name="designazionerdl",
            name="approvata_da",
        ),
        migrations.RemoveField(
            model_name="designazionerdl",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="designazionerdl",
            name="user",
        ),
        migrations.RemoveField(
            model_name="subdelega",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="subdelega",
            name="user",
        ),
        migrations.AddField(
            model_name="batchgenerazionedocumenti",
            name="created_by_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="creato da (email)"
            ),
        ),
        migrations.AddField(
            model_name="campagnareclutamento",
            name="created_by_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="creato da (email)"
            ),
        ),
        migrations.AddField(
            model_name="designazionerdl",
            name="approvata_da_email",
            field=models.EmailField(
                blank=True,
                help_text="Email del Delegato che ha approvato la bozza",
                max_length=254,
                verbose_name="approvata da (email)",
            ),
        ),
        migrations.AddField(
            model_name="designazionerdl",
            name="created_by_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="creato da (email)"
            ),
        ),
        migrations.AddField(
            model_name="subdelega",
            name="created_by_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="creato da (email)"
            ),
        ),
        migrations.AlterField(
            model_name="delegatodilista",
            name="territorio_municipi",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista di numeri di municipio (per grandi città)",
                verbose_name="municipi",
            ),
        ),
        migrations.AlterField(
            model_name="subdelega",
            name="municipi",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista di numeri di municipio (per grandi città)",
                verbose_name="municipi",
            ),
        ),
    ]
