# Generated by Django 5.2.10 on 2026-02-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0010_remove_user_fk_use_email"),
        ("sections", "0010_alter_sectionassignment_rdl_registration_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CampagnaReclutamento",
        ),
    ]
