# Generated by Django 5.2.11 on 2026-02-07 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0013_rename_delegatodelista_to_delegato"),
        ("elections", "0003_add_partition_bindings_remove_old_circumscriptions"),
        ("territory", "0003_replace_popolazione_with_sopra_15000"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchgenerazionedocumenti",
            name="sub_delega",
        ),
        migrations.AddField(
            model_name="batchgenerazionedocumenti",
            name="consultazione",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_documenti",
                to="elections.consultazioneelettorale",
                verbose_name="consultazione",
            ),
        ),
        migrations.AlterField(
            model_name="delegato",
            name="comuni",
            field=models.ManyToManyField(
                blank=True,
                help_text="Comuni di competenza",
                related_name="delegati",
                to="territory.comune",
                verbose_name="comuni",
            ),
        ),
        migrations.AlterField(
            model_name="delegato",
            name="province",
            field=models.ManyToManyField(
                blank=True,
                help_text="Province di competenza",
                related_name="delegati",
                to="territory.provincia",
                verbose_name="province",
            ),
        ),
        migrations.AlterField(
            model_name="delegato",
            name="regioni",
            field=models.ManyToManyField(
                blank=True,
                help_text="Regioni di competenza",
                related_name="delegati",
                to="territory.regione",
                verbose_name="regioni",
            ),
        ),
    ]
