# Generated by Django 5.2.11 on 2026-02-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0016_processo_designazione"),
        ("elections", "0004_add_data_version_and_has_subdelegations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processodesignazione",
            name="consultazione",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processi_designazione",
                to="elections.consultazioneelettorale",
                verbose_name="consultazione",
            ),
        ),
        migrations.AlterField(
            model_name="processodesignazione",
            name="data_generazione_individuale",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="data generazione individuale"
            ),
        ),
        migrations.AlterField(
            model_name="processodesignazione",
            name="documento_cumulativo",
            field=models.FileField(
                blank=True,
                help_text="PDF riepilogativo multi-pagina",
                null=True,
                upload_to="deleghe/processi/",
                verbose_name="documento cumulativo",
            ),
        ),
        migrations.AlterField(
            model_name="processodesignazione",
            name="documento_individuale",
            field=models.FileField(
                blank=True,
                help_text="ZIP con PDF individuali (uno per sezione)",
                null=True,
                upload_to="deleghe/processi/",
                verbose_name="documento individuale",
            ),
        ),
    ]
