# Generated by Django 5.2.11 on 2026-02-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0017_alter_processodesignazione_consultazione_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processodesignazione",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INDIVIDUALE", "Individuale (uno per sezione)"),
                    ("RIEPILOGATIVO", "Riepilogativo (cumulativo)"),
                ],
                help_text="Tipo di documento (INDIVIDUALE/RIEPILOGATIVO) - per retrocompatibilità con vecchio frontend",
                max_length=20,
                null=True,
                verbose_name="tipo documento",
            ),
        ),
    ]
