# Generated by Django for processo field

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delegations', '0019_processo_designazione_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designazionerdl',
            name='processo',
            field=models.ForeignKey(
                help_text='Processo di designazione a cui appartiene questa designazione',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='designazioni',
                to='delegations.processodesignazione',
                verbose_name='processo designazione'
            ),
        ),
    ]
