# Generated by Django 5.2.11 on 2026-02-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0020_alter_designazionerdl_processo"),
    ]

    operations = [
        migrations.AddField(
            model_name="processodesignazione",
            name="sezione_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array di ID sezioni per cui generare designazioni",
                verbose_name="sezioni selezionate",
            ),
        ),
        migrations.AlterField(
            model_name="processodesignazione",
            name="documento_individuale",
            field=models.FileField(
                blank=True,
                help_text="PDF multi-pagina con una pagina per sezione",
                null=True,
                upload_to="deleghe/processi/",
                verbose_name="documento individuale",
            ),
        ),
    ]
