# Generated by Django 5.2.11 on 2026-02-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0021_add_sezione_ids_to_processo"),
    ]

    operations = [
        migrations.AddField(
            model_name="processodesignazione",
            name="email_inviate_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando sono state inviate le email agli RDL",
                null=True,
                verbose_name="data invio email",
            ),
        ),
        migrations.AddField(
            model_name="processodesignazione",
            name="email_inviate_da",
            field=models.EmailField(
                blank=True,
                help_text="Chi ha avviato l'invio delle email",
                max_length=254,
                verbose_name="email inviate da",
            ),
        ),
        migrations.AddField(
            model_name="processodesignazione",
            name="n_email_fallite",
            field=models.IntegerField(
                default=0,
                help_text="Totale email fallite",
                verbose_name="numero email fallite",
            ),
        ),
        migrations.AddField(
            model_name="processodesignazione",
            name="n_email_inviate",
            field=models.IntegerField(
                default=0,
                help_text="Totale email inviate con successo",
                verbose_name="numero email inviate",
            ),
        ),
        migrations.CreateModel(
            name="EmailDesignazioneLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destinatario_email",
                    models.EmailField(
                        max_length=254, verbose_name="email destinatario"
                    ),
                ),
                (
                    "destinatario_nome",
                    models.CharField(max_length=200, verbose_name="nome destinatario"),
                ),
                (
                    "tipo_rdl",
                    models.CharField(
                        choices=[
                            ("EFFETTIVO", "Effettivo"),
                            ("SUPPLENTE", "Supplente"),
                            ("EFFETTIVO+SUPPLENTE", "Effettivo + Supplente"),
                        ],
                        help_text="Ruolo RDL - può avere entrambi i ruoli",
                        max_length=30,
                        verbose_name="tipo RDL",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Inviata"),
                            ("FAILED", "Fallita"),
                            ("BOUNCED", "Rimbalzata"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                        verbose_name="stato",
                    ),
                ),
                (
                    "errore",
                    models.TextField(blank=True, verbose_name="messaggio errore"),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="oggetto")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="data invio"),
                ),
                (
                    "sent_by_email",
                    models.EmailField(max_length=254, verbose_name="inviata da"),
                ),
                (
                    "designazione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="delegations.designazionerdl",
                        verbose_name="designazione",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="delegations.processodesignazione",
                        verbose_name="processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "log email designazione",
                "verbose_name_plural": "log email designazioni",
                "db_table": "delegations_emaildesignazionelog",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["processo", "destinatario_email"],
                        name="delegations_process_78d20a_idx",
                    ),
                    models.Index(fields=["stato"], name="delegations_stato_4e6fe1_idx"),
                ],
            },
        ),
    ]
