# Generated by Django 5.2.11 on 2026-03-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegations', '0022_processodesignazione_email_inviate_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processodesignazione',
            name='stato',
            field=models.CharField(choices=[('SELEZIONE_TEMPLATE', 'Selezione Template'), ('BOZZA', 'Bozza (designazioni create)'), ('IN_GENERAZIONE', 'Generazione PDF in corso'), ('GENERATO', 'PDF Generati'), ('APPROVATO', 'Confermato'), ('ANNULLATO', 'Annullato'), ('INVIATO', 'Inviato a Prefettura'), ('TEST', 'Test (designazioni temporanee)')], default='SELEZIONE_TEMPLATE', max_length=30, verbose_name='stato'),
        ),
    ]
