# Generated by Django 5.2.10 on 2026-01-31 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="nome"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("SCRUTINY", "Scrutinio"),
                            ("INCIDENT", "Segnalazione"),
                            ("DELEGATION", "Delega"),
                        ],
                        max_length=20,
                        verbose_name="tipo template",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descrizione"),
                ),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="templates/",
                        verbose_name="file template",
                    ),
                ),
                (
                    "variables_schema",
                    models.JSONField(
                        default=dict,
                        help_text="Schema JSON delle variabili accettate",
                        verbose_name="schema variabili",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="attivo")),
                ("version", models.IntegerField(default=1, verbose_name="versione")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="ultimo aggiornamento"
                    ),
                ),
            ],
            options={
                "verbose_name": "template",
                "verbose_name_plural": "template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        default=dict,
                        help_text="Dati usati per generare il documento",
                        verbose_name="dati input",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="generated/%Y/%m/",
                        verbose_name="file PDF",
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(blank=True, null=True, verbose_name="URL PDF"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data generazione"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="generato da",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_documents",
                        to="documents.template",
                        verbose_name="template",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento generato",
                "verbose_name_plural": "documenti generati",
                "ordering": ["-generated_at"],
            },
        ),
    ]
