# Generated by Django 5.2.11 on 2026-02-04 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='confirmation_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP conferma'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data conferma'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='event_id',
            field=models.CharField(blank=True, help_text='ID evento Redis per audit trail', max_length=100, null=True, verbose_name='ID evento'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='preview_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='scadenza preview'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='review_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='token revisione'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='status',
            field=models.CharField(choices=[('PREVIEW', 'Preview (pending confirmation)'), ('CONFIRMED', 'Confirmed (immutable)'), ('EXPIRED', 'Expired (never confirmed)'), ('CANCELLED', 'Cancelled by user')], default='PREVIEW', max_length=10, verbose_name='stato'),
        ),
        migrations.AddField(
            model_name='template',
            name='field_mappings',
            field=models.JSONField(default=list, help_text='Lista di {area: {x, y, width, height}, jsonpath: "$.field", type: "text|loop"}', verbose_name='mappatura campi'),
        ),
        migrations.AddField(
            model_name='template',
            name='loop_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configurazione loop: {type: "single|multi_page", rows_first_page: N, rows_per_page: M, data_source: "$.path"}', null=True, verbose_name='configurazione loop'),
        ),
        migrations.AddField(
            model_name='template',
            name='merge_mode',
            field=models.CharField(choices=[('SINGLE_DOC_PER_RECORD', 'Un documento per record'), ('MULTI_PAGE_LOOP', 'Documento multi-pagina con loop')], default='SINGLE_DOC_PER_RECORD', max_length=25, verbose_name='modalità unione'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['review_token'], name='documents_g_review__85482a_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['status', 'preview_expires_at'], name='documents_g_status_8dabc8_idx'),
        ),
    ]
