# Generated by Django 5.2.11 on 2026-02-04 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_generateddocument_confirmation_ip_and_more"),
        ("elections", "0003_add_partition_bindings_remove_old_circumscriptions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="template",
            options={
                "ordering": ["consultazione", "name"],
                "verbose_name": "template",
                "verbose_name_plural": "template",
            },
        ),
        migrations.AddField(
            model_name="template",
            name="consultazione",
            field=models.ForeignKey(
                blank=True,
                help_text="Consultazione elettorale a cui appartiene questo template",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="elections.consultazioneelettorale",
                verbose_name="consultazione elettorale",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nome"),
        ),
        migrations.AlterField(
            model_name="template",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("DELEGATION", "Delega Sub-Delegato"),
                    ("DESIGNATION", "Designazione RDL"),
                ],
                max_length=20,
                verbose_name="tipo template",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="template",
            unique_together={("consultazione", "name")},
        ),
    ]
