# Generated by Django 5.2.11 on 2026-02-04 18:13

from django.db import migrations


def assign_active_consultazione(apps, schema_editor):
    """Assign active consultazione to existing templates."""
    Template = apps.get_model('documents', 'Template')
    ConsultazioneElettorale = apps.get_model('elections', 'ConsultazioneElettorale')

    # Get active consultazione (or first one)
    consultazione = ConsultazioneElettorale.objects.filter(is_attiva=True).first()
    if not consultazione:
        consultazione = ConsultazioneElettorale.objects.first()

    if consultazione:
        # Assign to all templates without consultazione
        Template.objects.filter(consultazione__isnull=True).update(
            consultazione=consultazione
        )


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_template_options_template_consultazione_and_more"),
        ("elections", "0001_initial"),  # Ensure elections app is migrated
    ]

    operations = [
        migrations.RunPython(assign_active_consultazione, reverse_code=migrations.RunPython.noop),
    ]
