# Generated by Django 5.2.11 on 2026-02-05 18:59

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_assign_consultazione_to_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Codice identificativo univoco (es: DELEGATION, DESIGNATION_SINGLE)",
                        max_length=50,
                        unique=True,
                        verbose_name="codice",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome visualizzato (es: Delega Sub-Delegato)",
                        max_length=100,
                        verbose_name="nome",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrizione del caso d'uso",
                        verbose_name="descrizione",
                    ),
                ),
                (
                    "default_schema",
                    models.JSONField(
                        default=dict,
                        help_text="Schema JSON di esempio per questo tipo di template",
                        verbose_name="schema predefinito",
                    ),
                ),
                (
                    "default_merge_mode",
                    models.CharField(
                        choices=[
                            ("SINGLE_DOC_PER_RECORD", "Un documento per record"),
                            ("MULTI_PAGE_LOOP", "Documento multi-pagina con loop"),
                        ],
                        default="SINGLE_DOC_PER_RECORD",
                        help_text="Modalità di generazione documenti per questo tipo",
                        max_length=25,
                        verbose_name="modalità unione predefinita",
                    ),
                ),
                (
                    "use_case",
                    models.TextField(
                        blank=True,
                        help_text="Quando usare questo tipo di template",
                        verbose_name="caso d'uso",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="attivo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="ultimo aggiornamento"
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo template",
                "verbose_name_plural": "tipi template",
                "ordering": ["code"],
            },
        ),
        # Rename existing template_type to old_template_type
        migrations.RenameField(
            model_name="template",
            old_name="template_type",
            new_name="old_template_type",
        ),
        # Add new nullable ForeignKey field
        migrations.AddField(
            model_name="template",
            name="template_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo di template che definisce schema e modalità unione",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="documents.templatetype",
                verbose_name="tipo template",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="merge_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SINGLE_DOC_PER_RECORD", "Un documento per record"),
                    ("MULTI_PAGE_LOOP", "Documento multi-pagina con loop"),
                ],
                help_text="Modalità unione (se vuoto, usa default del template_type)",
                max_length=25,
                null=True,
                verbose_name="modalità unione",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="template_file",
            field=models.FileField(
                blank=True,
                help_text="File PDF template (rinominato automaticamente con UUID)",
                null=True,
                upload_to=documents.models.template_upload_path,
                verbose_name="file template",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="variables_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Schema JSON delle variabili accettate (eredita da template_type se vuoto)",
                verbose_name="schema variabili",
            ),
        ),
    ]
