# Generated by Django 5.2.11 on 2026-02-05 18:59

from django.db import migrations


def migrate_template_types(apps, schema_editor):
    """
    Migrate existing templates from old_template_type CharField to template_type ForeignKey.

    Mapping:
    - 'DELEGATION' → TemplateType(code='DELEGATION')
    - 'DESIGNATION' → TemplateType(code='DESIGNATION_MULTI') if name contains 'individuale'
    - 'DESIGNATION' → TemplateType(code='DESIGNATION_SINGLE') if name contains 'singola'
    """
    Template = apps.get_model('documents', 'Template')
    TemplateType = apps.get_model('documents', 'TemplateType')

    # Get TemplateType instances
    try:
        delegation_type = TemplateType.objects.get(code='DELEGATION')
        designation_single_type = TemplateType.objects.get(code='DESIGNATION_SINGLE')
        designation_multi_type = TemplateType.objects.get(code='DESIGNATION_MULTI')
    except TemplateType.DoesNotExist:
        print("ERROR: TemplateType instances not found. Run populate_template_types first.")
        return

    # Migrate templates
    for template in Template.objects.all():
        old_type = template.old_template_type

        if not old_type:
            print(f"WARNING: Template '{template.name}' has no old_template_type, skipping")
            continue

        if old_type == 'DELEGATION':
            template.template_type = delegation_type
            print(f"✓ Migrated '{template.name}': DELEGATION → {delegation_type.code}")

        elif old_type == 'DESIGNATION':
            # Heuristic based on template name
            name_lower = template.name.lower()

            if 'singola' in name_lower:
                template.template_type = designation_single_type
                print(f"✓ Migrated '{template.name}': DESIGNATION → {designation_single_type.code} (singola)")

            elif 'individuale' in name_lower or 'riepilogativa' in name_lower or 'riepilogativo' in name_lower:
                template.template_type = designation_multi_type
                print(f"✓ Migrated '{template.name}': DESIGNATION → {designation_multi_type.code} (multi)")

            else:
                # Default to MULTI if unclear
                template.template_type = designation_multi_type
                print(f"⚠ Migrated '{template.name}': DESIGNATION → {designation_multi_type.code} (default)")

        else:
            print(f"ERROR: Unknown old_template_type '{old_type}' for template '{template.name}'")
            continue

        template.save()

    print("\n✅ Template type migration completed!")


def reverse_migrate(apps, schema_editor):
    """Reverse migration: copy template_type FK back to old_template_type CharField."""
    Template = apps.get_model('documents', 'Template')

    for template in Template.objects.all():
        if template.template_type:
            code = template.template_type.code

            # Map back to old choices
            if code == 'DELEGATION':
                template.old_template_type = 'DELEGATION'
            elif code in ['DESIGNATION_SINGLE', 'DESIGNATION_MULTI']:
                template.old_template_type = 'DESIGNATION'

            template.template_type = None
            template.save()


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_add_template_type_model"),
    ]

    operations = [
        migrations.RunPython(migrate_template_types, reverse_migrate),
    ]
