# Generated by Django 5.2.11 on 2026-02-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_migrate_template_types_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="old_template_type",
        ),
    ]
