# Generated by Django 5.2.11 on 2026-02-07 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_remove_template_variables_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="template_type",
            field=models.ForeignKey(
                help_text="Tipo di template che definisce schema e modalità unione",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="documents.templatetype",
                verbose_name="tipo template",
            ),
        ),
    ]
