# Generated by Django 5.2.11 on 2026-02-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_alter_template_template_type"),
        ("elections", "0004_add_data_version_and_has_subdelegations"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="owner_email",
            field=models.EmailField(
                blank=True,
                help_text="Se valorizzato, il template è personale e visibile solo al proprietario. Se null, è generico e visibile a tutti.",
                max_length=254,
                null=True,
                verbose_name="proprietario (email)",
            ),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["owner_email", "is_active"],
                name="documents_t_owner_e_98a420_idx",
            ),
        ),
    ]
