# Generated by Django 5.2.11 on 2026-03-07 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0008_chatsession_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True, verbose_name='Telegram update ID')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram user ID')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='chat ID')),
                ('update_type', models.CharField(max_length=30, verbose_name='tipo update')),
                ('processing_status', models.CharField(choices=[('OK', 'Elaborato'), ('ERROR', 'Errore'), ('SKIPPED', 'Ignorato')], max_length=10, verbose_name='stato elaborazione')),
                ('error_message', models.TextField(blank=True, verbose_name='messaggio errore')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='elaborato il')),
            ],
            options={
                'verbose_name': 'log update Telegram',
                'verbose_name_plural': 'log update Telegram',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalChannelConversationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='telegram', max_length=20, verbose_name='canale')),
                ('telegram_chat_id', models.BigIntegerField(verbose_name='Telegram chat ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram user ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultimo aggiornamento')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='ai_assistant.chatsession', verbose_name='sessione chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_conversation_links', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'link conversazione esterna',
                'verbose_name_plural': 'link conversazioni esterne',
                'indexes': [models.Index(fields=['channel', 'telegram_chat_id', 'telegram_user_id'], name='telegram_bo_channel_726c34_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramIdentityBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, verbose_name='Telegram user ID')),
                ('telegram_chat_id', models.BigIntegerField(verbose_name='Telegram chat ID')),
                ('phone_number_normalized', models.CharField(max_length=20, verbose_name='numero telefono normalizzato')),
                ('binding_status', models.CharField(choices=[('PENDING', 'In attesa'), ('ACTIVE', 'Attivo'), ('REVOKED', 'Revocato'), ('BLOCKED', 'Bloccato')], default='PENDING', max_length=10, verbose_name='stato binding')),
                ('first_bound_at', models.DateTimeField(blank=True, null=True, verbose_name='primo binding')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='ultimo messaggio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultimo aggiornamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bindings', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'binding Telegram',
                'verbose_name_plural': 'binding Telegram',
                'indexes': [models.Index(fields=['telegram_user_id', 'binding_status'], name='telegram_bo_telegra_fbbd18_idx'), models.Index(fields=['user', 'binding_status'], name='telegram_bo_user_id_3b914c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('binding_status', 'ACTIVE')), fields=('telegram_user_id',), name='unique_active_telegram_user'), models.UniqueConstraint(condition=models.Q(('binding_status', 'ACTIVE')), fields=('user',), name='unique_active_internal_user')],
            },
        ),
    ]
