# Generated by Django 5.2.10 on 2026-02-01 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="descrizione"),
                ),
                (
                    "icona",
                    models.CharField(
                        default="fa-folder",
                        help_text="Classe FontAwesome (es. fa-file-pdf, fa-book)",
                        max_length=50,
                        verbose_name="icona FontAwesome",
                    ),
                ),
                ("ordine", models.IntegerField(default=0, verbose_name="ordine")),
                ("is_attiva", models.BooleanField(default=True, verbose_name="attiva")),
            ],
            options={
                "verbose_name": "categoria documento",
                "verbose_name_plural": "categorie documenti",
                "ordering": ["ordine", "nome"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="descrizione"),
                ),
                (
                    "icona",
                    models.CharField(
                        default="fa-question-circle",
                        help_text="Classe FontAwesome (es. fa-vote-yea, fa-calculator)",
                        max_length=50,
                        verbose_name="icona FontAwesome",
                    ),
                ),
                ("ordine", models.IntegerField(default=0, verbose_name="ordine")),
                ("is_attiva", models.BooleanField(default=True, verbose_name="attiva")),
            ],
            options={
                "verbose_name": "categoria FAQ",
                "verbose_name_plural": "categorie FAQ",
                "ordering": ["ordine", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=200, verbose_name="titolo")),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="descrizione"),
                ),
                (
                    "file",
                    models.FileField(upload_to="documenti/%Y/%m/", verbose_name="file"),
                ),
                (
                    "tipo_file",
                    models.CharField(
                        blank=True,
                        help_text="Determinato automaticamente dal file",
                        max_length=20,
                        verbose_name="tipo file",
                    ),
                ),
                (
                    "dimensione",
                    models.BigIntegerField(
                        default=0, verbose_name="dimensione (bytes)"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("TUTTI", "Tutte le consultazioni"),
                            ("REFERENDUM", "Solo Referendum"),
                            ("COMUNALI", "Solo Comunali"),
                            ("REGIONALI", "Solo Regionali"),
                            ("POLITICHE", "Solo Politiche"),
                            ("EUROPEE", "Solo Europee"),
                            ("SPECIFICO", "Consultazione specifica"),
                        ],
                        default="TUTTI",
                        help_text="Determina in quali consultazioni il documento è visibile",
                        max_length=20,
                        verbose_name="visibilità",
                    ),
                ),
                (
                    "is_pubblico",
                    models.BooleanField(
                        default=True,
                        help_text="Se False, visibile solo a utenti autenticati",
                        verbose_name="pubblico",
                    ),
                ),
                (
                    "in_evidenza",
                    models.BooleanField(
                        default=False,
                        help_text="Mostrato in cima alla lista",
                        verbose_name="in evidenza",
                    ),
                ),
                ("is_attivo", models.BooleanField(default=True, verbose_name="attivo")),
                ("ordine", models.IntegerField(default=0, verbose_name="ordine")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="data modifica"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documenti",
                        to="resources.categoriadocumento",
                        verbose_name="categoria",
                    ),
                ),
                (
                    "consultazione_specifica",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo se scope = SPECIFICO",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documenti_specifici",
                        to="elections.consultazioneelettorale",
                        verbose_name="consultazione specifica",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documenti_creati",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento",
                "verbose_name_plural": "documenti",
                "ordering": ["-in_evidenza", "ordine", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domanda", models.CharField(max_length=500, verbose_name="domanda")),
                ("risposta", models.TextField(verbose_name="risposta")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("TUTTI", "Tutte le consultazioni"),
                            ("REFERENDUM", "Solo Referendum"),
                            ("COMUNALI", "Solo Comunali"),
                            ("REGIONALI", "Solo Regionali"),
                            ("POLITICHE", "Solo Politiche"),
                            ("EUROPEE", "Solo Europee"),
                            ("SPECIFICO", "Consultazione specifica"),
                        ],
                        default="TUTTI",
                        help_text="Determina in quali consultazioni la FAQ è visibile",
                        max_length=20,
                        verbose_name="visibilità",
                    ),
                ),
                (
                    "is_pubblico",
                    models.BooleanField(
                        default=True,
                        help_text="Se False, visibile solo a utenti autenticati",
                        verbose_name="pubblico",
                    ),
                ),
                (
                    "in_evidenza",
                    models.BooleanField(
                        default=False,
                        help_text="Mostrata in cima alla lista",
                        verbose_name="in evidenza",
                    ),
                ),
                ("is_attivo", models.BooleanField(default=True, verbose_name="attivo")),
                ("ordine", models.IntegerField(default=0, verbose_name="ordine")),
                (
                    "visualizzazioni",
                    models.PositiveIntegerField(
                        default=0, verbose_name="visualizzazioni"
                    ),
                ),
                (
                    "utile_si",
                    models.PositiveIntegerField(
                        default=0, verbose_name="voti utile: sì"
                    ),
                ),
                (
                    "utile_no",
                    models.PositiveIntegerField(
                        default=0, verbose_name="voti utile: no"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="data modifica"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faqs",
                        to="resources.categoriafaq",
                        verbose_name="categoria",
                    ),
                ),
                (
                    "consultazione_specifica",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo se scope = SPECIFICO",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_specifiche",
                        to="elections.consultazioneelettorale",
                        verbose_name="consultazione specifica",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faq_create",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": [
                    "-in_evidenza",
                    "categoria__ordine",
                    "ordine",
                    "-created_at",
                ],
            },
        ),
    ]
