# Generated by Django 5.2.10 on 2026-02-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="url_esterno",
            field=models.URLField(
                blank=True,
                help_text="Link a documento esterno (es. Ministero). Alternativa a file caricato.",
                max_length=500,
                verbose_name="URL esterno",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="File caricato. Alternativa a URL esterno.",
                null=True,
                upload_to="documenti/%Y/%m/",
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="tipo_file",
            field=models.CharField(
                blank=True,
                help_text="Determinato automaticamente dal file o dall'URL",
                max_length=20,
                verbose_name="tipo file",
            ),
        ),
    ]
