# Generated by Django 5.2.10 on 2026-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_add_url_esterno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documento",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="created_by",
        ),
        migrations.AddField(
            model_name="documento",
            name="created_by_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="creato da (email)"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="created_by_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="creato da (email)"
            ),
        ),
    ]
