#!/bin/bash
#
# Script per configurare Firebase dopo aver creato il progetto dalla console.
#
# Uso:
#   ./scripts/setup-firebase.sh
#
# Prerequisiti:
#   1. Aver creato il progetto Firebase su https://console.firebase.google.com/
#   2. Aver aggiunto una Web App e ottenuto la config
#   3. Aver generato la VAPID key (Cloud Messaging → Web Push certificates)
#

set -e

echo "=== Setup Firebase per AInaudi PWA ==="
echo ""

# Read values
read -p "Firebase API Key: " API_KEY
read -p "Firebase Auth Domain (es. ainaudi-prod.firebaseapp.com): " AUTH_DOMAIN
read -p "Firebase Project ID [ainaudi-prod]: " PROJECT_ID
PROJECT_ID=${PROJECT_ID:-ainaudi-prod}
read -p "Firebase Storage Bucket (es. ainaudi-prod.firebasestorage.app): " STORAGE_BUCKET
read -p "Firebase Messaging Sender ID: " SENDER_ID
read -p "Firebase App ID: " APP_ID
read -p "VAPID Key (Web Push certificate): " VAPID_KEY

echo ""
echo "=== Aggiornamento file ==="

# 1. Update .env
echo ""
echo "→ Aggiorno .env..."
sed -i '' "s|^VITE_FIREBASE_API_KEY=.*|VITE_FIREBASE_API_KEY=$API_KEY|" .env
sed -i '' "s|^VITE_FIREBASE_AUTH_DOMAIN=.*|VITE_FIREBASE_AUTH_DOMAIN=$AUTH_DOMAIN|" .env
sed -i '' "s|^VITE_FIREBASE_PROJECT_ID=.*|VITE_FIREBASE_PROJECT_ID=$PROJECT_ID|" .env
sed -i '' "s|^VITE_FIREBASE_STORAGE_BUCKET=.*|VITE_FIREBASE_STORAGE_BUCKET=$STORAGE_BUCKET|" .env
sed -i '' "s|^VITE_FIREBASE_MESSAGING_SENDER_ID=.*|VITE_FIREBASE_MESSAGING_SENDER_ID=$SENDER_ID|" .env
sed -i '' "s|^VITE_FIREBASE_APP_ID=.*|VITE_FIREBASE_APP_ID=$APP_ID|" .env
sed -i '' "s|^VITE_FCM_VAPID_KEY=.*|VITE_FCM_VAPID_KEY=$VAPID_KEY|" .env

# 2. Update firebase-config.js (for service worker)
echo "→ Aggiorno public/firebase-config.js..."
cat > public/firebase-config.js << EOF
/**
 * Firebase configuration for service worker.
 * Auto-generated by scripts/setup-firebase.sh
 */
const FIREBASE_CONFIG = {
    apiKey: '$API_KEY',
    authDomain: '$AUTH_DOMAIN',
    projectId: '$PROJECT_ID',
    storageBucket: '$STORAGE_BUCKET',
    messagingSenderId: '$SENDER_ID',
    appId: '$APP_ID',
};
EOF

echo ""
echo "=== Fatto! ==="
echo ""
echo "Prossimi passi:"
echo "  1. npm run dev        # per testare in locale"
echo "  2. npm run build      # per buildare"
echo "  3. ./deploy.sh        # per deployare"
echo ""
