# Generated by Django 5.2.10 on 2026-01-31 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("territory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="indirizzo email"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome da visualizzare nell'applicazione",
                        max_length=255,
                        verbose_name="nome visualizzato",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="numero di telefono",
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, null=True, verbose_name="URL avatar"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="ultimo aggiornamento"
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="ultimo IP di login"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "utente",
                "verbose_name_plural": "utenti",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CREATE", "Creazione"),
                            ("UPDATE", "Modifica"),
                            ("DELETE", "Eliminazione"),
                            ("ASSIGN_ROLE", "Assegnazione ruolo"),
                            ("REVOKE_ROLE", "Revoca ruolo"),
                            ("DELEGATE", "Delega"),
                            ("SUBMIT_DATA", "Invio dati"),
                            ("GENERATE_PDF", "Generazione PDF"),
                        ],
                        max_length=20,
                        verbose_name="azione",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="modello target"
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID target"
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="dettagli"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="indirizzo IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "log audit",
                "verbose_name_plural": "log audit",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "action"], name="core_auditl_user_id_4f5b78_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="core_auditl_timesta_80074f_idx"
                    ),
                    models.Index(
                        fields=["target_model", "target_id"],
                        name="core_auditl_target__315580_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdentityProviderLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("magic_link", "Magic Link"),
                            ("m5s_sso", "M5S SSO"),
                        ],
                        max_length=20,
                        verbose_name="provider",
                    ),
                ),
                (
                    "provider_uid",
                    models.CharField(
                        help_text="ID univoco dell'utente presso il provider",
                        max_length=255,
                        verbose_name="ID provider",
                    ),
                ),
                (
                    "provider_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email associata al provider (può differire da quella principale)",
                        max_length=254,
                        null=True,
                        verbose_name="email provider",
                    ),
                ),
                (
                    "linked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data collegamento"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ultimo utilizzo"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, questo è il provider principale per l'utente",
                        verbose_name="provider primario",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "collegamento identity provider",
                "verbose_name_plural": "collegamenti identity provider",
                "ordering": ["-is_primary", "-last_used_at"],
                "unique_together": {("provider", "provider_uid")},
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Amministratore"),
                            ("DELEGATE", "Delegato"),
                            ("SUBDELEGATE", "Sub-delegato"),
                            ("RDL", "Responsabile di Lista"),
                            ("KPI_VIEWER", "Visualizzatore KPI"),
                            ("OBSERVER", "Osservatore"),
                        ],
                        max_length=20,
                        verbose_name="ruolo",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("global", "Globale"),
                            ("regione", "Regione"),
                            ("provincia", "Provincia"),
                            ("comune", "Comune"),
                            ("municipio", "Municipio"),
                            ("sezione", "Sezione"),
                        ],
                        help_text="Tipo di ambito territoriale",
                        max_length=20,
                        null=True,
                        verbose_name="tipo ambito",
                    ),
                ),
                (
                    "scope_value",
                    models.CharField(
                        blank=True,
                        help_text='Valore specifico dell\'ambito (es. "Roma", "Municipio I")',
                        max_length=100,
                        null=True,
                        verbose_name="valore ambito",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data assegnazione"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="valido da"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="valido fino a"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="attivo")),
                ("notes", models.TextField(blank=True, verbose_name="note")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assegnato da",
                    ),
                ),
                (
                    "scope_comune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments",
                        to="territory.comune",
                        verbose_name="comune",
                    ),
                ),
                (
                    "scope_provincia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments",
                        to="territory.provincia",
                        verbose_name="provincia",
                    ),
                ),
                (
                    "scope_regione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments",
                        to="territory.regione",
                        verbose_name="regione",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "assegnazione ruolo",
                "verbose_name_plural": "assegnazioni ruoli",
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "role"], name="core_roleas_user_id_5d23e1_idx"
                    ),
                    models.Index(
                        fields=["scope_type", "scope_value"],
                        name="core_roleas_scope_t_b075b9_idx",
                    ),
                ],
            },
        ),
    ]
