# Generated by Django 5.2.10 on 2026-02-03 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_delete_identityproviderlink"),
        ("elections", "0003_add_partition_bindings_remove_old_circumscriptions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="core_auditl_user_id_4f5b78_idx",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="roleassignment",
            name="assigned_by",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_email",
            field=models.EmailField(
                blank=True,
                help_text="Email dell'utente che ha eseguito l'azione",
                max_length=254,
                verbose_name="utente (email)",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="assigned_by_email",
            field=models.EmailField(
                blank=True,
                help_text="Email di chi ha assegnato il ruolo",
                max_length=254,
                verbose_name="assegnato da (email)",
            ),
        ),
        migrations.AlterField(
            model_name="roleassignment",
            name="consultazione",
            field=models.ForeignKey(
                help_text="Consultazione per cui il ruolo è valido (obbligatorio)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to="elections.consultazioneelettorale",
                verbose_name="consultazione",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user_email", "action"], name="core_auditl_user_em_6c24c0_idx"
            ),
        ),
    ]
