# Generated by Django 5.2.10 on 2026-02-03 11:30

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0004_remove_user_fk_use_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gruppo",
            fields=[],
            options={
                "verbose_name": "gruppo",
                "verbose_name_plural": "gruppi",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
