# Generated by Django 5.2.11 on 2026-02-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_custom_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "can_manage_territory",
                        "Can manage territory (regions, provinces, comuni, sections)",
                    ),
                    ("can_view_kpi", "Can view KPI dashboard"),
                    ("can_manage_elections", "Can manage elections and ballots"),
                    ("can_manage_delegations", "Can manage delegations chain"),
                    ("can_manage_rdl", "Can manage RDL registrations"),
                    ("can_manage_campaign", "Can manage RDL recruitment campaigns"),
                    ("has_scrutinio_access", "Can enter section scrutinio data"),
                    ("can_view_resources", "Can view resources and documents"),
                    ("can_ask_to_ai_assistant", "Can use AI assistant chatbot"),
                    ("can_generate_documents", "Can generate PDF documents"),
                    ("can_manage_incidents", "Can manage incident reports"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
