# Generated by Django 5.2.11 on 2026-02-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_ai_assistant_permission_to_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_view_dashboard', 'Can view dashboard'), ('can_manage_territory', 'Can manage territory (regions, provinces, comuni)'), ('can_manage_elections', 'Can manage elections and ballots'), ('can_manage_campaign', 'Can manage RDL recruitment campaigns'), ('can_manage_rdl', 'Can manage RDL registrations'), ('can_manage_sections', 'Can manage electoral sections'), ('can_manage_mappatura', 'Can manage RDL to sections mapping'), ('can_manage_delegations', 'Can manage delegations chain'), ('can_manage_designazioni', 'Can manage formal RDL designations'), ('can_manage_templates', 'Can manage PDF templates'), ('can_generate_documents', 'Can generate PDF documents'), ('has_scrutinio_access', 'Can enter section scrutinio data'), ('can_view_resources', 'Can view resources and documents'), ('can_view_live_results', 'Can view live election results'), ('can_view_kpi', 'Can view KPI dashboard'), ('can_manage_mass_email', 'Can manage mass email templates and sending'), ('can_ask_to_ai_assistant', 'Can use AI assistant chatbot'), ('can_manage_incidents', 'Can manage incident reports')]},
        ),
    ]
