# Generated by Django 5.2.11 on 2026-03-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_custompermission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.CharField(blank=True, help_text='Codice PIN alternativo per login (configurato da admin, per utenti che non ricevono email)', max_length=20, null=True, verbose_name='PIN di accesso'),
        ),
    ]
