# Generated by Django 5.2.10 on 2026-01-31 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("territory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Utente"), ("assistant", "Assistente")],
                        max_length=20,
                        verbose_name="ruolo",
                    ),
                ),
                ("content", models.TextField(verbose_name="contenuto")),
                (
                    "sources_cited",
                    models.JSONField(
                        blank=True,
                        help_text="IDs delle fonti usate nella risposta",
                        null=True,
                        verbose_name="fonti citate",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
            ],
            options={
                "verbose_name": "messaggio chat",
                "verbose_name_plural": "messaggi chat",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titolo")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("FAQ", "FAQ"),
                            ("PROCEDURE", "Procedura"),
                            ("SLIDE", "Slide"),
                            ("MANUAL", "Manuale"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("content", models.TextField(verbose_name="contenuto")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="ultimo aggiornamento"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="attivo")),
            ],
            options={
                "verbose_name": "fonte conoscenza",
                "verbose_name_plural": "fonti conoscenza",
                "ordering": ["source_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        blank=True,
                        help_text="es. SCRUTINY, INCIDENT",
                        max_length=50,
                        null=True,
                        verbose_name="contesto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="ultimo aggiornamento"
                    ),
                ),
                (
                    "sezione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to="territory.sezioneelettorale",
                        verbose_name="sezione",
                    ),
                ),
            ],
            options={
                "verbose_name": "sessione chat",
                "verbose_name_plural": "sessioni chat",
                "ordering": ["-updated_at"],
            },
        ),
    ]
