# Generated by Django 5.2.10 on 2026-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="user",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user_email",
            field=models.EmailField(
                default="", max_length=254, verbose_name="utente (email)"
            ),
        ),
    ]
