# Generated by Django 5.2.11 on 2026-02-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0005_add_embedding_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgesource",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="URL del documento PDF originale (per preview)",
                max_length=500,
                verbose_name="URL sorgente",
            ),
        ),
    ]
