# Generated by Django 5.2.11 on 2026-02-12 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0006_add_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="parent_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Sessione da cui è stato fatto il branch (edit messaggio)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="ai_assistant.chatsession",
                verbose_name="sessione parent",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Titolo auto-generato dal primo messaggio",
                max_length=100,
                verbose_name="titolo",
            ),
        ),
    ]
