# Generated by Django 5.2.11 on 2026-03-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_add_title_and_branching'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dati aggiuntivi per funzionalità agentiche (es. pending_incident)', verbose_name='metadati'),
        ),
    ]
