# Generated by Django 5.2.12 on 2026-03-07 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0008_chatsession_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="chat_attachments/%Y/%m/%d/", verbose_name="file"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Immagine"),
                            ("AUDIO", "Audio"),
                            ("DOCUMENT", "Documento"),
                        ],
                        max_length=20,
                        verbose_name="tipo file",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME type"),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="nome file"),
                ),
                ("file_size", models.IntegerField(verbose_name="dimensione (bytes)")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="ai_assistant.chatmessage",
                        verbose_name="messaggio",
                    ),
                ),
            ],
            options={
                "verbose_name": "allegato chat",
                "verbose_name_plural": "allegati chat",
            },
        ),
    ]
