# Generated by Django 5.2.10 on 2026-01-31 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elections", "0001_initial"),
        ("territory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatiSezione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "elettori_maschi",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="elettori maschi"
                    ),
                ),
                (
                    "elettori_femmine",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="elettori femmine"
                    ),
                ),
                (
                    "votanti_maschi",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="votanti maschi"
                    ),
                ),
                (
                    "votanti_femmine",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="votanti femmine"
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Tutti i dati inseriti",
                        verbose_name="completato",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Dati verificati da un referente",
                        verbose_name="verificato",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data verifica"
                    ),
                ),
                (
                    "inserito_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data inserimento"
                    ),
                ),
                (
                    "aggiornato_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="ultimo aggiornamento"
                    ),
                ),
                (
                    "consultazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dati_sezioni",
                        to="elections.consultazioneelettorale",
                        verbose_name="consultazione",
                    ),
                ),
                (
                    "inserito_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dati_sezioni_inseriti",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="inserito da",
                    ),
                ),
                (
                    "sezione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dati",
                        to="territory.sezioneelettorale",
                        verbose_name="sezione",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sezioni_verificate",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="verificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "dati sezione",
                "verbose_name_plural": "dati sezioni",
                "ordering": ["sezione__comune", "sezione__numero"],
                "unique_together": {("sezione", "consultazione")},
            },
        ),
        migrations.CreateModel(
            name="DatiScheda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schede_ricevute",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="schede ricevute"
                    ),
                ),
                (
                    "schede_autenticate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="schede autenticate"
                    ),
                ),
                (
                    "schede_bianche",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="schede bianche"
                    ),
                ),
                (
                    "schede_nulle",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="schede nulle"
                    ),
                ),
                (
                    "schede_contestate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="schede contestate"
                    ),
                ),
                (
                    "voti",
                    models.JSONField(
                        blank=True,
                        help_text='\nStruttura voti dipende dal tipo scheda:\n- Referendum: {"si": 523, "no": 300}\n- Europee: {"liste": {"M5S": 250, "PD": 180}, "preferenze": {"FERRARA LAURA": 45}}\n- Politiche: {"uninominale": {...}, "liste": {...}}\n- Comunali: {"sindaco": {...}, "liste": {...}, "preferenze": {...}}\n        ',
                        null=True,
                        verbose_name="voti",
                    ),
                ),
                (
                    "errori_validazione",
                    models.TextField(
                        blank=True,
                        help_text="Eventuali errori di validazione rilevati",
                        null=True,
                        verbose_name="errori validazione",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True,
                        help_text="False se ci sono errori di validazione",
                        verbose_name="valido",
                    ),
                ),
                (
                    "inserito_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data inserimento"
                    ),
                ),
                (
                    "aggiornato_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="ultimo aggiornamento"
                    ),
                ),
                (
                    "scheda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dati",
                        to="elections.schedaelettorale",
                        verbose_name="scheda",
                    ),
                ),
                (
                    "dati_sezione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schede",
                        to="data.datisezione",
                        verbose_name="dati sezione",
                    ),
                ),
            ],
            options={
                "verbose_name": "dati scheda",
                "verbose_name_plural": "dati schede",
                "ordering": ["scheda__ordine"],
                "unique_together": {("dati_sezione", "scheda")},
            },
        ),
        migrations.CreateModel(
            name="SectionDataHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campo",
                    models.CharField(max_length=100, verbose_name="campo modificato"),
                ),
                (
                    "valore_precedente",
                    models.TextField(
                        blank=True, null=True, verbose_name="valore precedente"
                    ),
                ),
                (
                    "valore_nuovo",
                    models.TextField(
                        blank=True, null=True, verbose_name="valore nuovo"
                    ),
                ),
                (
                    "modificato_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data modifica"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="indirizzo IP"
                    ),
                ),
                (
                    "dati_scheda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="data.datischeda",
                        verbose_name="dati scheda",
                    ),
                ),
                (
                    "dati_sezione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="data.datisezione",
                        verbose_name="dati sezione",
                    ),
                ),
                (
                    "modificato_da",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modifiche_dati",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "storico dati sezione",
                "verbose_name_plural": "storico dati sezioni",
                "ordering": ["-modificato_at"],
            },
        ),
        migrations.CreateModel(
            name="SectionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("RDL", "Responsabile di Lista"),
                            ("SUPPLENTE", "Supplente"),
                        ],
                        default="RDL",
                        max_length=20,
                        verbose_name="ruolo",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data assegnazione"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="attivo")),
                ("notes", models.TextField(blank=True, verbose_name="note")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assegnato da",
                    ),
                ),
                (
                    "consultazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_assignments",
                        to="elections.consultazioneelettorale",
                        verbose_name="consultazione",
                    ),
                ),
                (
                    "sezione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="territory.sezioneelettorale",
                        verbose_name="sezione",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "assegnazione sezione",
                "verbose_name_plural": "assegnazioni sezioni",
                "ordering": ["sezione__comune", "sezione__numero"],
                "indexes": [
                    models.Index(
                        fields=["user", "consultazione"],
                        name="sections_se_user_id_a47914_idx",
                    ),
                    models.Index(
                        fields=["sezione", "consultazione"],
                        name="sections_se_sezione_52f596_idx",
                    ),
                ],
                "unique_together": {("sezione", "consultazione", "user")},
            },
        ),
    ]
