# Generated by Django 5.2.10 on 2026-02-01 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
        ("territory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RdlRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="email"
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                ("cognome", models.CharField(max_length=100, verbose_name="cognome")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefono"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "In attesa di approvazione"),
                            ("APPROVED", "Approvato"),
                            ("REJECTED", "Rifiutato"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="stato",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data richiesta"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data approvazione"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="motivo rifiuto"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="note")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SELF", "Auto-registrazione"),
                            ("IMPORT", "Import CSV"),
                            ("MANUAL", "Inserimento manuale"),
                        ],
                        default="SELF",
                        max_length=20,
                        verbose_name="origine",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rdl_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approvato da",
                    ),
                ),
                (
                    "comune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdl_registrations",
                        to="territory.comune",
                        verbose_name="comune",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opzionale, per grandi città con municipi",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rdl_registrations",
                        to="territory.municipio",
                        verbose_name="municipio",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rdl_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "registrazione RDL",
                "verbose_name_plural": "registrazioni RDL",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(fields=["email"], name="sections_rd_email_158b0f_idx"),
                    models.Index(
                        fields=["status"], name="sections_rd_status_98af44_idx"
                    ),
                    models.Index(
                        fields=["comune", "status"],
                        name="sections_rd_comune__dccb08_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["PENDING", "APPROVED"])),
                        fields=("email", "comune"),
                        name="unique_active_rdl_per_comune",
                    )
                ],
            },
        ),
    ]
