# Generated by Django 5.2.10 on 2026-02-01 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_add_rdl_registration"),
        ("territory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rdlregistration",
            name="unique_active_rdl_per_comune",
        ),
        migrations.AddField(
            model_name="rdlregistration",
            name="comune_nascita",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="comune di nascita"
            ),
        ),
        migrations.AddField(
            model_name="rdlregistration",
            name="comune_residenza",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="residente nel comune di"
            ),
        ),
        migrations.AddField(
            model_name="rdlregistration",
            name="data_nascita",
            field=models.DateField(
                blank=True, null=True, verbose_name="data di nascita"
            ),
        ),
        migrations.AddField(
            model_name="rdlregistration",
            name="indirizzo_residenza",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="indirizzo di residenza"
            ),
        ),
        migrations.AddField(
            model_name="rdlregistration",
            name="seggio_preferenza",
            field=models.CharField(
                blank=True,
                help_text="Dove fare il Rappresentante di Lista",
                max_length=255,
                verbose_name="seggio/plesso di preferenza",
            ),
        ),
        migrations.AlterField(
            model_name="rdlregistration",
            name="comune",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rdl_registrations",
                to="territory.comune",
                verbose_name="comune operativo",
            ),
        ),
        migrations.AlterField(
            model_name="rdlregistration",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                help_text="Per grandi città con municipi",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rdl_registrations",
                to="territory.municipio",
                verbose_name="municipio di appartenenza",
            ),
        ),
        migrations.AlterField(
            model_name="rdlregistration",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="recapito telefonico"
            ),
        ),
    ]
