# Generated by Django 5.2.10 on 2026-02-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_add_rdl_extra_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rdlregistration",
            name="telefono",
            field=models.CharField(max_length=20, verbose_name="recapito telefonico"),
        ),
    ]
