# Generated by Django 5.2.10 on 2026-02-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
        ("data", "0009_remove_user_fk_use_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionassignment",
            name="rdl_registration",
            field=models.ForeignKey(
                help_text="RDL dal pool approvati - cancellando l'RDL si cancella l'assegnazione",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_assignments",
                to="campaign.rdlregistration",
                verbose_name="registrazione RDL",
            ),
        ),
        migrations.DeleteModel(
            name="RdlRegistration",
        ),
    ]
