# Generated by Django 5.2.10 on 2026-02-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_alter_sectionassignment_rdl_registration_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sectionassignment",
            new_name="data_sectio_rdl_reg_826205_idx",
            old_name="sections_se_rdl_reg_f85e02_idx",
        ),
        migrations.RenameIndex(
            model_name="sectionassignment",
            new_name="data_sectio_sezione_b6c02b_idx",
            old_name="sections_se_sezione_52f596_idx",
        ),
    ]
