# Generated by Django 5.2.11 on 2026-02-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0012_add_optimistic_locking"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="datischeda",
            new_name="data_datisc_dati_se_edea83_idx",
            old_name="data_datisc_datisez_version_idx",
        ),
        migrations.RenameIndex(
            model_name="datisezione",
            new_name="data_datise_sezione_a7a99a_idx",
            old_name="data_datise_sezione_version_idx",
        ),
        migrations.AlterField(
            model_name="datischeda",
            name="aggiornato_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Deprecato - usare updated_at",
                verbose_name="aggiornamento legacy",
            ),
        ),
        migrations.AlterField(
            model_name="datisezione",
            name="aggiornato_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Deprecato - usare updated_at",
                verbose_name="aggiornamento legacy",
            ),
        ),
    ]
