# Generated by Django 5.2.10 on 2026-01-31 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("territory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultazioneElettorale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text='es. "Elezioni 8-9 Giugno 2024"',
                        max_length=200,
                        verbose_name="nome",
                    ),
                ),
                ("data_inizio", models.DateField(verbose_name="data inizio")),
                (
                    "data_fine",
                    models.DateField(
                        help_text="Può essere 2 giorni", verbose_name="data fine"
                    ),
                ),
                (
                    "is_attiva",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, questa è la consultazione attualmente in corso",
                        verbose_name="attiva",
                    ),
                ),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="descrizione"),
                ),
            ],
            options={
                "verbose_name": "consultazione elettorale",
                "verbose_name_plural": "consultazioni elettorali",
                "ordering": ["-data_inizio"],
            },
        ),
        migrations.CreateModel(
            name="SchedaElettorale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text='es. "Quesito 1 - Cittadinanza", "Camera", "Senato"',
                        max_length=200,
                        verbose_name="nome",
                    ),
                ),
                (
                    "colore",
                    models.CharField(
                        blank=True,
                        help_text='es. "verde chiaro", "rosa", "gialla"',
                        max_length=50,
                        null=True,
                        verbose_name="colore",
                    ),
                ),
                (
                    "ordine",
                    models.IntegerField(
                        default=0,
                        help_text="Ordine di visualizzazione",
                        verbose_name="ordine",
                    ),
                ),
                (
                    "testo_quesito",
                    models.TextField(
                        blank=True,
                        help_text="Testo completo del quesito referendario",
                        null=True,
                        verbose_name="testo quesito",
                    ),
                ),
                (
                    "schema_voti",
                    models.JSONField(
                        default=dict,
                        help_text='\nSchema dati per questa scheda. Esempi:\n- Referendum: {"tipo": "si_no"}\n- Camera/Senato: {"tipo": "liste_candidati", "uninominale": true, "plurinominale": true}\n- Europee: {"tipo": "liste_preferenze", "max_preferenze": 3}\n- Comunali <15k: {"tipo": "sindaco_lista", "preferenze": 1}\n- Comunali >=15k: {"tipo": "sindaco_liste", "preferenze": 2, "ballottaggio": true}\n        ',
                        verbose_name="schema voti",
                    ),
                ),
            ],
            options={
                "verbose_name": "scheda elettorale",
                "verbose_name_plural": "schede elettorali",
                "ordering": ["tipo_elezione", "ordine"],
            },
        ),
        migrations.CreateModel(
            name="CircoscrizioneCamera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField(unique=True, verbose_name="numero")),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "regioni",
                    models.ManyToManyField(
                        related_name="circoscrizioni_camera",
                        to="territory.regione",
                        verbose_name="regioni",
                    ),
                ),
            ],
            options={
                "verbose_name": "circoscrizione Camera",
                "verbose_name_plural": "circoscrizioni Camera",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="CircoscrizioneEuropee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice",
                    models.CharField(
                        choices=[
                            ("NORD_OVEST", "Italia Nord-Occidentale"),
                            ("NORD_EST", "Italia Nord-Orientale"),
                            ("CENTRO", "Italia Centrale"),
                            ("SUD", "Italia Meridionale"),
                            ("ISOLE", "Italia Insulare"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="codice",
                    ),
                ),
                (
                    "regioni",
                    models.ManyToManyField(
                        related_name="circoscrizioni_europee",
                        to="territory.regione",
                        verbose_name="regioni",
                    ),
                ),
            ],
            options={
                "verbose_name": "circoscrizione Europee",
                "verbose_name_plural": "circoscrizioni Europee",
                "ordering": ["codice"],
            },
        ),
        migrations.CreateModel(
            name="CircoscrizioneSenato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regione",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circoscrizione_senato",
                        to="territory.regione",
                        verbose_name="regione",
                    ),
                ),
            ],
            options={
                "verbose_name": "circoscrizione Senato",
                "verbose_name_plural": "circoscrizioni Senato",
            },
        ),
        migrations.CreateModel(
            name="ListaElettorale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "nome_breve",
                    models.CharField(
                        blank=True,
                        help_text='Abbreviazione (es. "M5S", "PD")',
                        max_length=50,
                        verbose_name="nome breve",
                    ),
                ),
                (
                    "simbolo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="simboli/",
                        verbose_name="simbolo",
                    ),
                ),
                (
                    "ordine_scheda",
                    models.IntegerField(
                        default=0,
                        help_text="Posizione sulla scheda",
                        verbose_name="ordine scheda",
                    ),
                ),
                (
                    "coalizione",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lista capofila della coalizione",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liste_collegate",
                        to="elections.listaelettorale",
                        verbose_name="coalizione",
                    ),
                ),
                (
                    "scheda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liste",
                        to="elections.schedaelettorale",
                        verbose_name="scheda",
                    ),
                ),
            ],
            options={
                "verbose_name": "lista elettorale",
                "verbose_name_plural": "liste elettorali",
                "ordering": ["scheda", "ordine_scheda"],
            },
        ),
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
                ("cognome", models.CharField(max_length=200, verbose_name="cognome")),
                (
                    "data_nascita",
                    models.DateField(
                        blank=True, null=True, verbose_name="data di nascita"
                    ),
                ),
                (
                    "luogo_nascita",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="luogo di nascita"
                    ),
                ),
                (
                    "posizione_lista",
                    models.IntegerField(
                        blank=True,
                        help_text="Per candidati plurinominali",
                        null=True,
                        verbose_name="posizione in lista",
                    ),
                ),
                (
                    "collegio_uninominale",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="collegio uninominale",
                    ),
                ),
                (
                    "is_sindaco",
                    models.BooleanField(
                        default=False, verbose_name="candidato sindaco"
                    ),
                ),
                (
                    "is_presidente",
                    models.BooleanField(
                        default=False, verbose_name="candidato presidente"
                    ),
                ),
                (
                    "lista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidati",
                        to="elections.listaelettorale",
                        verbose_name="lista",
                    ),
                ),
                (
                    "scheda",
                    models.ForeignKey(
                        blank=True,
                        help_text="Per candidati uninominali",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidati_uninominali",
                        to="elections.schedaelettorale",
                        verbose_name="scheda",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidato",
                "verbose_name_plural": "candidati",
                "ordering": ["lista", "posizione_lista", "cognome"],
            },
        ),
        migrations.CreateModel(
            name="TipoElezione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("REFERENDUM", "Referendum"),
                            ("POLITICHE_CAMERA", "Politiche - Camera"),
                            ("POLITICHE_SENATO", "Politiche - Senato"),
                            ("EUROPEE", "Europee"),
                            ("REGIONALI", "Regionali"),
                            ("COMUNALI", "Comunali"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "ambito_nazionale",
                    models.BooleanField(
                        default=False,
                        help_text="True per referendum, politiche, europee",
                        verbose_name="ambito nazionale",
                    ),
                ),
                (
                    "comuni",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Per comunali (lista comuni che votano)",
                        related_name="tipi_elezione",
                        to="territory.comune",
                        verbose_name="comuni",
                    ),
                ),
                (
                    "consultazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipi_elezione",
                        to="elections.consultazioneelettorale",
                        verbose_name="consultazione",
                    ),
                ),
                (
                    "regione",
                    models.ForeignKey(
                        blank=True,
                        help_text="Per regionali",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipi_elezione",
                        to="territory.regione",
                        verbose_name="regione",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo elezione",
                "verbose_name_plural": "tipi elezione",
                "unique_together": {("consultazione", "tipo", "regione")},
            },
        ),
        migrations.AddField(
            model_name="schedaelettorale",
            name="tipo_elezione",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schede",
                to="elections.tipoelezione",
                verbose_name="tipo elezione",
            ),
        ),
    ]
