# Generated by Django 5.2.10 on 2026-02-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_schedaelettorale_turno"),
        ("territory", "0002_add_territorial_partitions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circoscrizioneeuropee",
            name="regioni",
        ),
        migrations.RemoveField(
            model_name="circoscrizionesenato",
            name="regione",
        ),
        migrations.AlterField(
            model_name="tipoelezione",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("REFERENDUM", "Referendum"),
                    ("POLITICHE_CAMERA", "Politiche - Camera"),
                    ("POLITICHE_SENATO", "Politiche - Senato"),
                    ("EUROPEE", "Europee"),
                    ("REGIONALI", "Regionali"),
                    ("COMUNALI", "Comunali"),
                    ("MUNICIPALI", "Municipali"),
                ],
                max_length=20,
                verbose_name="tipo",
            ),
        ),
        migrations.CreateModel(
            name="BallotActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="attiva")),
                (
                    "partition_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballot_activations",
                        to="territory.territorialpartitionunit",
                        verbose_name="unità partizione",
                    ),
                ),
                (
                    "scheda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="elections.schedaelettorale",
                        verbose_name="scheda",
                    ),
                ),
            ],
            options={
                "verbose_name": "attivazione scheda",
                "verbose_name_plural": "attivazioni schede",
                "unique_together": {("scheda", "partition_unit")},
            },
        ),
        migrations.CreateModel(
            name="CandidatePartitionEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posizione",
                    models.IntegerField(
                        blank=True,
                        help_text="Posizione in lista (per plurinominale)",
                        null=True,
                        verbose_name="posizione",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partition_eligibilities",
                        to="elections.candidato",
                        verbose_name="candidato",
                    ),
                ),
                (
                    "lista",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lista di appartenenza in questa partizione (per plurinominale)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_eligibilities",
                        to="elections.listaelettorale",
                        verbose_name="lista",
                    ),
                ),
                (
                    "partition_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_eligibilities",
                        to="territory.territorialpartitionunit",
                        verbose_name="unità partizione",
                    ),
                ),
            ],
            options={
                "verbose_name": "eleggibilità candidato per partizione",
                "verbose_name_plural": "eleggibilità candidati per partizione",
                "unique_together": {("candidato", "partition_unit")},
            },
        ),
        migrations.CreateModel(
            name="ElectionPartitionBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "consultazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partition_bindings",
                        to="elections.consultazioneelettorale",
                        verbose_name="consultazione",
                    ),
                ),
                (
                    "partition_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="election_bindings",
                        to="territory.territorialpartitionset",
                        verbose_name="set partizioni",
                    ),
                ),
            ],
            options={
                "verbose_name": "binding partizioni elezione",
                "verbose_name_plural": "binding partizioni elezioni",
                "unique_together": {("consultazione", "partition_set")},
            },
        ),
        migrations.DeleteModel(
            name="CircoscrizioneCamera",
        ),
        migrations.DeleteModel(
            name="CircoscrizioneEuropee",
        ),
        migrations.DeleteModel(
            name="CircoscrizioneSenato",
        ),
    ]
