# Generated by Django 5.2.10 on 2026-02-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delegations", "0010_remove_user_fk_use_email"),
        ("elections", "0003_add_partition_bindings_remove_old_circumscriptions"),
        ("territory", "0002_add_territorial_partitions"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampagnaReclutamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome identificativo della campagna",
                        max_length=200,
                        verbose_name="nome",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL pubblico: /campagna/{slug}",
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "descrizione",
                    models.TextField(
                        blank=True,
                        help_text="Descrizione mostrata nella pagina di registrazione",
                        verbose_name="descrizione",
                    ),
                ),
                (
                    "data_apertura",
                    models.DateTimeField(
                        help_text="Quando la campagna diventa accessibile",
                        verbose_name="data apertura",
                    ),
                ),
                (
                    "data_chiusura",
                    models.DateTimeField(
                        help_text="Quando la campagna termina",
                        verbose_name="data chiusura",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("BOZZA", "Bozza"),
                            ("ATTIVA", "Attiva"),
                            ("CHIUSA", "Chiusa"),
                        ],
                        default="BOZZA",
                        max_length=15,
                        verbose_name="stato",
                    ),
                ),
                (
                    "created_by_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="creato da (email)"
                    ),
                ),
                (
                    "richiedi_approvazione",
                    models.BooleanField(
                        default=True,
                        help_text="Se True, le registrazioni devono essere approvate manualmente",
                        verbose_name="richiedi approvazione",
                    ),
                ),
                (
                    "max_registrazioni",
                    models.IntegerField(
                        blank=True,
                        help_text="Numero massimo di registrazioni (null = illimitato)",
                        null=True,
                        verbose_name="max registrazioni",
                    ),
                ),
                (
                    "messaggio_conferma",
                    models.TextField(
                        blank=True,
                        help_text="Messaggio mostrato dopo la registrazione",
                        verbose_name="messaggio conferma",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="data modifica"),
                ),
                (
                    "consultazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campagne_reclutamento",
                        to="elections.consultazioneelettorale",
                        verbose_name="consultazione",
                    ),
                ),
                (
                    "delegato",
                    models.ForeignKey(
                        blank=True,
                        help_text="Delegato che ha creato la campagna",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campagne_reclutamento",
                        to="delegations.delegatodilista",
                        verbose_name="delegato",
                    ),
                ),
                (
                    "sub_delega",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sub-delegato che ha creato la campagna",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campagne_reclutamento",
                        to="delegations.subdelega",
                        verbose_name="sub-delega",
                    ),
                ),
                (
                    "territory_comuni",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Comuni dove è possibile registrarsi",
                        related_name="campagne_reclutamento",
                        to="territory.comune",
                        verbose_name="comuni",
                    ),
                ),
                (
                    "territory_province",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Province dove è possibile registrarsi",
                        related_name="campagne_reclutamento",
                        to="territory.provincia",
                        verbose_name="province",
                    ),
                ),
                (
                    "territory_regioni",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Regioni dove è possibile registrarsi",
                        related_name="campagne_reclutamento",
                        to="territory.regione",
                        verbose_name="regioni",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagna di Reclutamento",
                "verbose_name_plural": "Campagne di Reclutamento",
                "ordering": ["-data_apertura"],
            },
        ),
        migrations.CreateModel(
            name="RdlRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="email"
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                ("cognome", models.CharField(max_length=100, verbose_name="cognome")),
                (
                    "telefono",
                    models.CharField(max_length=20, verbose_name="recapito telefonico"),
                ),
                (
                    "comune_nascita",
                    models.CharField(max_length=100, verbose_name="comune di nascita"),
                ),
                ("data_nascita", models.DateField(verbose_name="data di nascita")),
                (
                    "comune_residenza",
                    models.CharField(
                        max_length=100, verbose_name="residente nel comune di"
                    ),
                ),
                (
                    "indirizzo_residenza",
                    models.CharField(
                        max_length=255, verbose_name="indirizzo di residenza"
                    ),
                ),
                (
                    "seggio_preferenza",
                    models.CharField(
                        blank=True,
                        help_text="Dove fare il Rappresentante di Lista",
                        max_length=255,
                        verbose_name="seggio/plesso di preferenza",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "In attesa di approvazione"),
                            ("APPROVED", "Approvato"),
                            ("REJECTED", "Rifiutato"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="stato",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data richiesta"
                    ),
                ),
                (
                    "approved_by_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="approvato da (email)"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data approvazione"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="motivo rifiuto"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="note")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SELF", "Auto-registrazione"),
                            ("IMPORT", "Import CSV"),
                            ("MANUAL", "Inserimento manuale"),
                            ("CAMPAGNA", "Campagna di reclutamento"),
                        ],
                        default="SELF",
                        max_length=20,
                        verbose_name="origine",
                    ),
                ),
                (
                    "campagna",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registrazioni",
                        to="campaign.campagnareclutamento",
                        verbose_name="campagna di reclutamento",
                    ),
                ),
                (
                    "comune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdl_registrations",
                        to="territory.comune",
                        verbose_name="comune operativo",
                    ),
                ),
                (
                    "consultazione",
                    models.ForeignKey(
                        blank=True,
                        help_text="Consultazione per cui l'RDL si è registrato",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdl_registrations",
                        to="elections.consultazioneelettorale",
                        verbose_name="consultazione",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        help_text="Per grandi città con municipi",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rdl_registrations",
                        to="territory.municipio",
                        verbose_name="municipio di appartenenza",
                    ),
                ),
            ],
            options={
                "verbose_name": "registrazione RDL",
                "verbose_name_plural": "registrazioni RDL",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="campagnareclutamento",
            index=models.Index(fields=["slug"], name="campaign_ca_slug_6ce7ca_idx"),
        ),
        migrations.AddIndex(
            model_name="campagnareclutamento",
            index=models.Index(
                fields=["stato", "data_apertura", "data_chiusura"],
                name="campaign_ca_stato_472334_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rdlregistration",
            index=models.Index(fields=["email"], name="campaign_rd_email_e6ad66_idx"),
        ),
        migrations.AddIndex(
            model_name="rdlregistration",
            index=models.Index(fields=["status"], name="campaign_rd_status_9d382b_idx"),
        ),
        migrations.AddIndex(
            model_name="rdlregistration",
            index=models.Index(
                fields=["comune", "status"], name="campaign_rd_comune__9c7ab6_idx"
            ),
        ),
    ]
