# Generated by Django 5.2.10 on 2026-02-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdlregistration",
            name="comune_domicilio",
            field=models.CharField(
                blank=True,
                help_text="Se fuorisede, comune dove lavora/studia",
                max_length=100,
                verbose_name="comune di domicilio",
            ),
        ),
        migrations.AddField(
            model_name="rdlregistration",
            name="fuorisede",
            field=models.BooleanField(
                blank=True,
                help_text="Lavora o studia in un comune diverso dalla residenza",
                null=True,
                verbose_name="fuorisede",
            ),
        ),
        migrations.AddField(
            model_name="rdlregistration",
            name="indirizzo_domicilio",
            field=models.CharField(
                blank=True,
                help_text="Se fuorisede, indirizzo di domicilio",
                max_length=255,
                verbose_name="indirizzo di domicilio",
            ),
        ),
    ]
