# Generated by Django 5.2.11 on 2026-02-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_add_fuorisede_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdlregistration',
            name='geocode_place_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Google Place ID'),
        ),
        migrations.AddField(
            model_name='rdlregistration',
            name='geocode_quality',
            field=models.CharField(blank=True, default='', help_text='ROOFTOP, RANGE_INTERPOLATED, GEOMETRIC_CENTER, APPROXIMATE', max_length=30, verbose_name='qualità geocodifica'),
        ),
        migrations.AddField(
            model_name='rdlregistration',
            name='geocode_source',
            field=models.CharField(blank=True, default='', help_text='es. "google", "manual"', max_length=30, verbose_name='sorgente geocodifica'),
        ),
        migrations.AddField(
            model_name='rdlregistration',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data geocodifica'),
        ),
        migrations.AddField(
            model_name='rdlregistration',
            name='latitudine',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitudine'),
        ),
        migrations.AddField(
            model_name='rdlregistration',
            name='longitudine',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitudine'),
        ),
    ]
