# Generated by Django 5.2.11 on 2026-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0003_rdl_geocode_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdlregistration",
            name="sezioni_vicine",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Top 10 sezioni elettorali più vicine [{id, numero, indirizzo, distanza_km}]",
                verbose_name="sezioni vicine",
            ),
        ),
    ]
