# Generated by Django 5.2.11 on 2026-02-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0004_rdl_sezioni_vicine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rdlregistration",
            name="sezioni_vicine",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Top 10 plessi più vicini [{indirizzo, distanza_km, sezioni: [numeri]}]",
                verbose_name="sezioni vicine",
            ),
        ),
    ]
