# Generated by Django 5.2.11 on 2026-02-20 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_alter_rdlregistration_sezioni_vicine'),
        ('elections', '0004_add_data_version_and_has_subdelegations'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome interno del template', max_length=200, verbose_name='nome template')),
                ('oggetto', models.CharField(help_text="Subject dell'email. Supporta variabili: {{ rdl.nome }}, {{ rdl.cognome }}, ecc.", max_length=500, verbose_name='oggetto email')),
                ('corpo', models.TextField(help_text='Body HTML con variabili Django template: {{ rdl.nome }}, {{ rdl.comune }}, ecc.', verbose_name='corpo email')),
                ('created_by_email', models.EmailField(blank=True, max_length=254, verbose_name='creato da (email)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data modifica')),
                ('consultazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to='elections.consultazioneelettorale', verbose_name='consultazione')),
            ],
            options={
                'verbose_name': 'Template Email',
                'verbose_name_plural': 'Template Email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MassEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('SUCCESS', 'Inviata'), ('FAILED', 'Fallita')], max_length=10, verbose_name='stato')),
                ('errore', models.TextField(blank=True, verbose_name='errore')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='data invio')),
                ('sent_by_email', models.EmailField(blank=True, max_length=254, verbose_name='inviato da (email)')),
                ('rdl_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_email_logs', to='campaign.rdlregistration', verbose_name='registrazione RDL')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_email_logs', to='campaign.emailtemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'Log Email Massiva',
                'verbose_name_plural': 'Log Email Massive',
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('template', 'rdl_registration'), name='unique_template_rdl_email')],
            },
        ),
    ]
